{
  "hash": "f87449f6a1690c6ad9e2663fafbb67a6",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: Detecting schroeder structural features\nsubtitle: Fine scale acoustic perception in zebra finches\nauthor: Marcelo Araya-Salas\ndate: \"2026-10-04\"\ntoc: true\ntoc-depth: 2\ntoc-location: left\nnumber-sections: true\nhighlight-style: pygments\nformat:\n  html:\n    df-print: kable\n    code-fold: true\n    code-tools: true\n    css: qmd.css\neditor_options: \n  chunk_output_type: console\n---\n\n\n\nSource code and data found at [https://github.com/maRce10/acoustic-fine-structure-methods](https://github.com/maRce10/acoustic-fine-structure-methods)\n\n\n::: {.cell}\n\n:::\n\n\n\n&nbsp; \n\n<!-- skyblue box -->\n\n<div class=\"alert alert-info\">\n\n# Purpose\n\n- Compare methods for measuring fine scale structural variation and periodicity in schroeders\n\n</div>\n\n&nbsp;\n\n<!-- light brown box -->\n<div class=\"alert alert-warning\">\n\n# Report overview\n\n  - [Synthetizing schroeders](#synthetizing-schroeders)\n  - [Measuring schroeder dissimilarity](#measuring-schroeder-dissimilarity)\n  - [Takeaways](#takeaways)\n  - [Additional figures](#additional-figures)\n\n</div>\n\n&nbsp;\n\n::: {.cell}\n\n```{.r .numberLines .lineAnchors .cell-code}\nsource(\"./scripts/MRM2.R\")\n\nwarbleR_options(parallel = 22)\n\nwave_col <- viridis(10)[7]\n```\n:::\n\n\n\n# Synthetizing schroeders\n\n## Function to make schroeders\n\n\n::: {.cell}\n\n```{.r .numberLines .lineAnchors .cell-code}\nqwindpc <- function(rftime, srate, sig) {\n  ramppts <- round((rftime / 1000) * srate)\n  hold1 <- seq(0, 1, length.out = ramppts + 1)\n  onramp <- sin(0.5 * pi * hold1)^2\n  offramp <- cos(0.5 * pi * hold1)^2\n  steady <- rep(1, length(sig) - (2 * ramppts) - 2)\n  wind <- c(onramp, steady, offramp)\n\n  if (length(wind) > length(sig)) {\n    print(\"Window not applied, block too short for window\")\n  } else {\n    sig <- wind * sig\n  }\n\n  return(sig)\n}\n\n\nmake_rep_schroeder <-\n  function(samp.rate = 44100,\n           f0,\n           dur = 1000,\n           save.wave = FALSE,\n           plot = TRUE,\n           n.components,\n           scalar = 1,\n           color = wave_col,\n           path = \".\",\n           file.name = NULL,\n           random.start = FALSE,\n           mfrow =  c(2, 1),\n           par = TRUE,\n           cex.oscillo = 1,\n           ...) {\n    \n      # duplicate duration if starting randomly\n    dur.mult <- if (random.start)  2 else 1\n    \n    # set time instances at which samples will be \"taken\"\n    t <- seq(1 / samp.rate, 1, by = 1 / samp.rate)\n    sumwavepos <- rep(0, samp.rate)\n\n    durpts <- round((dur * dur.mult / 1000) * samp.rate)\n \n    phase <- rep(0, n.components)\n    amplin <- rep(1, n.components)\n    f <- rep(0, n.components)\n\n    Ns <- 1:n.components\n\n    for (n in Ns) {\n      compnum <- n\n      phase[compnum] <- scalar * pi * compnum * (compnum - 1) / n.components\n      f[n] <- f0 + ((compnum - 1) * f0)\n    }\n\n    wave <- matrix(0, nrow = n.components, ncol = length(t))\n\n    for (i in Ns) {\n      wave[i, ] <- amplin[i] * cos((2 * pi * f[i] * t) + phase[i])\n      sumwavepos <- sumwavepos + wave[i, ]\n    }\n\n    # make sumwapos longer so it fit the target duration    \n    org.sumwavepos <- sumwavepos\n        \n    while(length(sumwavepos) < durpts) \n        sumwavepos <- c(sumwavepos, org.sumwavepos) \n\n    posschr <- sumwavepos[1:durpts] / max(abs(sumwavepos[1:durpts]))\n\n    # plot(t[1:length(posschr)], posschr, type = \"l\")\n\n    spectr <- fft(sumwavepos)\n    power <- abs(spectr)^2\n    sample <- length(t) / max(t)\n    freq <- (1:length(t)) * sample / length(t)\n    powerdb <- 10 * log10(power[1:(length(t) / 2)])\n\n    if (random.start){\n        strt <- sample(1:(length(posschr) / 2), 1)\n        posschr <- posschr[strt:(strt + (length(posschr) / 2) - 1)]\n    }\n    \n     posschr <- qwindpc(10, samp.rate, posschr)\n    posschr <- posschr / max(abs(posschr))\n    \n    wave_obj <- tuneR::normalize(tuneR::Wave(posschr, samp.rate = samp.rate, bit = 16), unit = \"16\")\n\n    if (plot) {\n      opar <- par()\n      opar$cin <- opar$cra <- opar$sci <- opar$cxy <- opar$din <- opar$csi <- opar$page <- NULL\n\n      # on.exit(par(opar))\n      if (par)\n      par(mfrow = mfrow, mar = c(5, 4, 0, 0) + 0.1)\n      \n      plot(\n        freq[1:(length(t) / 2)],\n        powerdb,\n        type = \"l\",\n        xlim = c(0, 5200),\n        xlab = \"Frequency (Hz)\",\n        ylab = \"Power(dB)\",\n        col =  color,\n        ... \n      )\n\n      seewave::oscillo(wave = wave_obj, colwave = color, cexlab = cex.oscillo, cexaxis = cex.oscillo)\n    }\n\n    # Save audio to a file\n    if (save.wave) {\n      if (is.null(file.name)) {\n        file.name <- paste0(\"f0-\", f0, \"_ncomp-\", n.components, \"_\", if (scalar == 1) \"pos\" else \"neg\", \".wav\")\n      }\n    writeWave(object = wave_obj, filename = file.path(path, file.name), extensible = FALSE)\n    \n    } else {\n      return(wave_obj)\n    }\n  }\n\nmake_single_schroeder <-\n  function(samp.rate = 44100,\n           f0,\n           # dur = 1000,\n           save.wave = FALSE,\n           plot = TRUE,\n           n.components,\n           scalar = 1,\n           color = wave_col,\n           path = \".\",\n           file.name = NULL,\n           mfrow = c(1, 1),\n           par = TRUE,\n           cex.oscillo = 1,\n           add.margin = TRUE,\n           ...) {\n    \n    # set time instances at which samples will be \"taken\"\n    t <- seq(1 / samp.rate, 1, by = 1 / samp.rate)\n    sumwavepos <- rep(0, samp.rate)\n \n    phase <- rep(0, n.components)\n    amplin <- rep(1, n.components)\n    f <- rep(0, n.components)\n\n    Ns <- 1:n.components\n\n    for (n in Ns) {\n      compnum <- n\n      phase[compnum] <- scalar * pi * compnum * (compnum - 1) / n.components\n      f[n] <- f0 + ((compnum - 1) * f0)\n    }\n\n    wave <- matrix(0, nrow = n.components, ncol = length(t))\n\n    for (i in Ns) {\n      wave[i, ] <- amplin[i] * cos((2 * pi * f[i] * t) + phase[i])\n      sumwavepos <- sumwavepos + wave[i, ]\n    }\n\n    schroeder <- sumwavepos[1:(round(samp.rate / f0))]\n    schroeder_length <- length(schroeder)\n    \n    if (plot){\n        par(mfrow = mfrow, mar = c(5, 4, 0, 0) + 0.1)\n        oscillo(wave = schroeder, f = f0, colwave = color, cexlab = cex.oscillo, cexaxis = cex.oscillo)\n    }    \n    \n    if (add.margin){\n        silence <- rep(0, samp.rate / 20)\n    schroeder <- c(silence, schroeder, silence)\n    }\n    \n    wave_obj <- tuneR::normalize(tuneR::Wave(schroeder, samp.rate = samp.rate, bit = 16), unit = \"16\")\n    \n    # Save audio to a file\n    if (save.wave) {\n      if (is.null(file.name)) {\n        file.name <- paste0(\"f0-\", f0, \"_ncomp-\", n.components, \"_\", if (scalar == 1) \"pos\" else \"neg\", \".wav\")\n      }\n    writeWave(object = wave_obj, filename = file.path(path, file.name), extensible = FALSE)\n    \n    return(data.frame(start = length(silence) / samp.rate, end = (length(silence) / samp.rate) + (schroeder_length / samp.rate)))\n    \n    } else {\n      return(wave_obj)\n    }\n  }\n```\n:::\n\n\n## Function to compute MFCC spectrograms\n\n::: {.cell}\n\n```{.r .numberLines .lineAnchors .cell-code}\nmel_spectro <- function(wave, ovlp = 0, wl = 512, palette = viridis::mako,\n    ncolors = 20, ncep = 20, tlab = \"Time (s)\", flab = \"MFCC\", flim = NULL,\n    plot = TRUE, axisY = TRUE, axisX = TRUE) {\n\n    f <- wave@samp.rate\n\n    # Convert flim from kHz to Hz if provided\n    if (!is.null(flim)) {\n        flim <- flim * 1000\n        # Calculate corresponding mel bands\n        mel_lim <- 1127 * log(1 + flim/700)\n    }\n\n    # common setting suggested by Sueur\n    mfccs <- melfcc(wave, sr = f, wintime = wl/f, hoptime = if (ovlp ==\n        0)\n        wl/f else wl/f * (ovlp/100), numcep = ncep, nbands = ncep * 2, fbtype = \"htkmel\",\n        dcttype = \"t3\", htklifter = TRUE, lifterexp = ncep - 1, frames_in_rows = FALSE,\n        spec_out = TRUE, minfreq = if (!is.null(flim))\n            flim[1] else 0, maxfreq = if (!is.null(flim))\n            flim[2] else f/2)\n\n    # convert NAs to 0s\n    mat <- t(mfccs$cepstra)\n    mat[is.na(mat)] <- max(mat, na.rm = TRUE)\n\n    # and plotting\n    if (plot) {\n        image(mat, col = palette(ncolors), axes = FALSE, xlab = tlab,\n            ylab = flab, xaxs = \"i\", yaxs = \"i\")\n        at <- seq(0, 1, length = 5)\n        times <- round(seq(0, duration(wave), length = 5), 2)\n        at_times <- times <- pretty(times)\n        at_times <- at_times/duration(wave)\n\n        # rescale x to deal with extra room in image() plot\n        rng_usr <- range(par()$usr)\n        at_times <- rng_usr[1] + ((at_times - 0)/(1 - 0)) * (rng_usr[2] -\n            rng_usr[1])\n\n        if (axisX)\n            axis(side = 1, at = at_times, labels = times)\n\n        if (axisY)\n            axis(side = 2, at = 0:(ncep - 1)/(ncep - 1), labels = 1:ncep)\n        box()\n    } else {\n        out <- list(time = round(seq(0, duration(wave), length = nrow(mat)),\n            2), mfcc = 1:ncep, amp = mat)\n\n        return(out)\n    }\n\n}\n```\n:::\n\n\n\n### Schroeder at 700 Hz with 7 components (harmonics) \n\nPositive\n\n::: {.cell}\n\n```{.r .numberLines .lineAnchors .cell-code}\nss <- make_single_schroeder(n.components = 7, samp.rate = 44100, f0 = 400,\n    dur = 25, save.wave = FALSE, plot = TRUE, scalar = -1, color = viridis(10)[3],\n    random.start = FALSE)\n```\n\n::: {.cell-output-display}\n![](1_schroeder_synthesis_and_method_comparison_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n\n```{.r .numberLines .lineAnchors .cell-code}\nms <- make_rep_schroeder(n.components = 7, samp.rate = 44100, f0 = 400,\n    dur = 25, save.wave = FALSE, plot = TRUE, scalar = -1, color = viridis(10)[3],\n    random.start = FALSE)\n```\n\n::: {.cell-output-display}\n![](1_schroeder_synthesis_and_method_comparison_files/figure-html/unnamed-chunk-4-2.png){width=672}\n:::\n:::\n\n\nNegative\n\n::: {.cell}\n\n```{.r .numberLines .lineAnchors .cell-code}\nms <- make_single_schroeder(n.components = 7, samp.rate = 44100, f0 = 400,\n    dur = 25, save.wave = FALSE, plot = TRUE, scalar = -1, color = viridis(10)[3])\n```\n\n::: {.cell-output-display}\n![](1_schroeder_synthesis_and_method_comparison_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n\n```{.r .numberLines .lineAnchors .cell-code}\nms <- make_rep_schroeder(n.components = 7, samp.rate = 44100, f0 = 400,\n    dur = 25, save.wave = FALSE, plot = TRUE, scalar = -1, color = viridis(10)[3])\n```\n\n::: {.cell-output-display}\n![](1_schroeder_synthesis_and_method_comparison_files/figure-html/unnamed-chunk-5-2.png){width=672}\n:::\n:::\n\n\n### Schroeder with 10 components\n\nPositive\n\n::: {.cell}\n\n```{.r .numberLines .lineAnchors .cell-code}\nms <- make_single_schroeder(n.components = 10, samp.rate = 44100,\n    f0 = 400, dur = 25, save.wave = FALSE, plot = TRUE, scalar = 1,\n    color = viridis(10)[3])\n```\n\n::: {.cell-output-display}\n![](1_schroeder_synthesis_and_method_comparison_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n\n```{.r .numberLines .lineAnchors .cell-code}\nms <- make_rep_schroeder(n.components = 10, samp.rate = 44100, f0 = 400,\n    dur = 25, save.wave = FALSE, plot = TRUE, scalar = 1, color = viridis(10)[3])\n```\n\n::: {.cell-output-display}\n![](1_schroeder_synthesis_and_method_comparison_files/figure-html/unnamed-chunk-6-2.png){width=672}\n:::\n:::\n\n\nNegative\n\n::: {.cell}\n\n```{.r .numberLines .lineAnchors .cell-code}\nms <- make_single_schroeder(n.components = 10, samp.rate = 44100,\n    f0 = 400, dur = 25, save.wave = FALSE, plot = TRUE, scalar = -1,\n    color = viridis(10)[3])\n```\n\n::: {.cell-output-display}\n![](1_schroeder_synthesis_and_method_comparison_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n\n```{.r .numberLines .lineAnchors .cell-code}\nms <- make_rep_schroeder(n.components = 10, samp.rate = 44100, f0 = 400,\n    dur = 25, save.wave = FALSE, plot = TRUE, scalar = -1, color = viridis(10)[3])\n```\n\n::: {.cell-output-display}\n![](1_schroeder_synthesis_and_method_comparison_files/figure-html/unnamed-chunk-7-2.png){width=672}\n:::\n:::\n\n\n## Make schroeders\n\n\nFull factorial design of the following features:\n\n - Components: from 5 to 25 (21 values)\n - Fundamental frequency: from 200 to 800 (7 values)\n - Phase: 1 and -1\n - 294 schroeders\n \nCreate schroeders as individual sound files: \n\n- 200 ms duration schroeders\n\n::: {.cell}\n\n```{.r .numberLines .lineAnchors .cell-code}\nshr_tab <- expand.grid(type = c(-1, 1), components = seq(5, 25, 1),\n    f0 = seq(200, 800, 100))\n\nnrow(shr_tab)\n\n\nshr_tab$name <- paste0(f_pad_zero(x = 1:nrow(shr_tab), width = 3),\n    \"_f0-\", shr_tab$f0, \"_ncomp-\", shr_tab$components, \"_\", ifelse(shr_tab$type ==\n        1, \"pos\", \"neg\"), \".wav\")\n\nout <- warbleR:::pblapply_wrblr_int(seq_len(nrow(shr_tab)), function(x) {\n    make_rep_schroeder(n.components = shr_tab$components[x], samp.rate = 44100,\n        f0 = shr_tab$f0[x], dur = 200, save.wave = TRUE, plot = FALSE,\n        scalar = shr_tab$type[x], color = \"red\", path = \"./data/processed/200ms_schroeders\",\n        file.name = shr_tab$name[x])\n})\n```\n:::\n\n\n- Single Schroeders\n\n::: {.cell}\n\n```{.r .numberLines .lineAnchors .cell-code}\nshr_tab <- expand.grid(type = c(-1, 1), components = seq(5, 25, 1),\n    f0 = seq(200, 800, 100))\n\nnrow(shr_tab)\n\nshr_tab$name <- paste0(f_pad_zero(x = 1:nrow(shr_tab), width = 3),\n    \"_f0-\", shr_tab$f0, \"_ncomp-\", shr_tab$components, \"_\", ifelse(shr_tab$type ==\n        1, \"pos\", \"neg\"), \".wav\")\n\nout <- warbleR:::pblapply_wrblr_int(seq_len(nrow(shr_tab)), function(x) {\n    df <- make_single_schroeder(n.components = shr_tab$components[x],\n        samp.rate = 44100, f0 = shr_tab$f0[x], dur = 200, save.wave = TRUE,\n        plot = FALSE, scalar = shr_tab$type[x], color = \"red\", path = \"./data/processed/single_schroeders\",\n        file.name = shr_tab$name[x])\n    df$sound.files <- shr_tab$name[x]\n    df$selec <- x\n\n    return(df)\n})\n\nsingle_anns <- do.call(rbind, out)\n\nwrite.csv(single_anns, \"./data/processed/single_schroeders_annotations.csv\",\n    row.names = FALSE)\n\nest_single_schr <- warbleR::selection_table(single_anns, path = \"./data/processed/single_schroeders\",\n    extended = TRUE)\n\nsaveRDS(est_single_schr, \"./data/processed/extended_selection_table_single_schroeders.RDS\")\n```\n:::\n\n\nPut repeated Schroeders into a extended selection table and a single sound file:\n\n::: {.cell}\n\n```{.r .numberLines .lineAnchors .cell-code}\n# fix start\nest_schr <- warbleR::selection_table(whole.recs = TRUE, path = \"./data/processed/200ms_schroeders\",\n    extended = TRUE)\n\nest_schr$bottom.freq <- (as.numeric(gsub(\"f0-\", \"\", (sapply(strsplit(est_schr$sound.files,\n    split = \"_\"), \"[[\", 2)))) - 50)/1000\n\nest_schr$top.freq <- freq_range(X = est_schr, threshold = 2, fsmooth = 0.8,\n    parallel = 13)$top.freq\n\nest_schr$f0 <- gsub(\"f0-\", \"\", sapply(strsplit(est_schr$sound.files,\n    split = \"_\"), \"[[\", 2))\n\nest_schr$label <- gsub(\"os.wav_1|eg.wav_1\", \"\", sapply(strsplit(est_schr$sound.files,\n    split = \"ncomp-\"), \"[[\", 2))\n\nsaveRDS(est_schr, \"./data/processed/extended_selection_table_200ms_schroeders.RDS\")\n\nmaster <- master_sound_file(X = est_schr, file.name = \"200ms_schroeder_master\",\n    dest.path = \"./data/processed/\", gap.duration = 0.8, cex = 14)\n\nwrite.csv(master, \"./data/processed/master_annotations_200ms_schroeders.csv\",\n    row.names = FALSE)\n\nmaster$f0 <- c(\"start_marker\", paste(\"f0\", est_schr$f0), \"\")\n\nmaster$label <- c(\"marker\", est_schr$label, \"marker\")\n\nRraven::exp_raven(master, file.name = \"200ms_schroeders\", path = \"./data/processed/\",\n    sound.file.path = \"./data/processed/\")\n\n# warbleR::full_spectrograms(master, path = './data/processed/',\n# sxrow =\n# duration(readWave('./data/processed/200ms_schroeder_master.wav'))\n# / 12, rows = 12, horizontal = TRUE, dest.path =\n# './data/processed/spectrograms', collevels = seq(-150, 0, 5),\n# labels = 'label', song = 'f0', wl = 2000)\n```\n:::\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .numberLines .lineAnchors .cell-code}\nexp_est(est_schr, path = \"./data/raw/extended_selection_table_schroeders_clips\",\n    file.name = \"annotations\")\n\nest_schr <- resample_est(est_schr, bit.depth = 32)\n\n# add silence\nfor (i in seq_len(nrow(est_schr))) {\n    wv <- read_sound_file(est_schr, index = i)\n    wv <- normalize(wv, unit = \"32\")\n\n    # make it a 200 ms cut\n    wv <- cutw(wave = wv, from = 0, to = 0.2, output = \"Wave\")\n    # sil <- runif(min = min(wv@left) / 7, max = max(wv@left) /\n    # 7, n = wv@samp.rate / 10) wv@left <- c(sil, wv@left, sil)\n    # wv <- addsilw(wave = wv, at = 'end', d = 0.1, f = 44100,\n    # output = 'Wave', ) wv <- addsilw(wave = wv, at = 'start',\n    # d = 0.1, f = 44100, output = 'Wave')\n    spectro(wv)\n\n    filename <- file.path(\"./data/raw/extended_selection_table_schroeders_clips/200ms\",\n        gsub(\"_1$\", \"\", est_schr$sound.files[i]))\n\n    writeWave(object = wv, filename = filename, extensible = FALSE)\n}\n\n# fix_wavs(path =\n# './data/raw/extended_selection_table_schroeders_clips/200ms')\n```\n:::\n\n\n\n# Measuring schroeder dissimilarity\n\nWe compare 9 methods for measuring acoustic structure (Table 1 in the manuscript), some of them implemented in more than one software package:\n\n- [Dynamic time warping (DTW) distances from schroeder waveform](#waveform-dtw) (repeated and single cycle)\n- [Waveform correlation](#waveform-correlation) (repeated and single cycle)\n- [Raven's spectrographic features](#ravens-spectrographic-features)\n- [warbleR's spectrographic features](#warblers-spectrographic-features)\n- [warbleR's MFCC features](#warblers-mfcc-features)\n- [warbleR's cross-correlation of fourier spectrograms](#warblers-fourier-cross-correlation)\n- [Raven's cross-correlation of fourier spectrograms](#ravens-fourier-cross-correlation)\n- [Raven's waveform correlation](#ravens-waveform-correlation)\n- [warbleR's cross-correlation of mel-frequency spectrograms](#warblers-mel-frequency-cross-correlation)\n- [Sound Analysis Pro harmonic goodness, pitch and amplitude modulation differences](#sap-harmonic-goodness)\n\nStatistical modeling:\n\n- [Multiple Regression on distance Matrices](https://search.r-project.org/CRAN/refmans/ecodist/html/MRM.html) \n - Model:   \n \\begin{align*}\n Dissimilarity &\\sim frequency + components + phase\n \\end{align*}\n- Response values scaled to make effect sizes comparable across models\n- Predictors were coded as pairwise binary matrices in which 0 means that calls in a dyad belong to the same level and 1 means calls belong to different levels \n\n## Waveform DTW\n\n- Using waveforms of 200 ms with repeated Schroeder cycles\n- Computed with `warbleR::waveform_similarity()`: amplitude vectors are normalized and resampled to 100 samples, one of them is duplicated and the other one is slid across the duplicated one (`type = \"sliding\"`)\n- The minimum DTW distance across sliding steps is kept as a dissimilarity measure\n- No band-pass filter is applied (`bp = NULL`)\n\n\n::: {.cell}\n\n```{.r .numberLines .lineAnchors .cell-code}\nschroeders <- readRDS(\"./data/processed/extended_selection_table_200ms_schroeders.RDS\")\n\nwv_sim <- waveform_similarity(X = schroeders, sim.method = \"DTW\",\n    type = \"sliding\", n = 100, bp = NULL, output = \"rectangular\")\n\n# remove selection number suffix ('-1') from IDs\nwv_sim <- data.frame(schr1 = gsub(\"-[0-9]+$\", \"\", wv_sim$id.1), schr2 = gsub(\"-[0-9]+$\",\n    \"\", wv_sim$id.2), dist = wv_sim$similarity)\n\nsaveRDS(wv_sim, \"./data/processed/dtw_distance_ac_segments_200ms_schroeders.RDS\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .numberLines .lineAnchors .cell-code}\nmin_dists <- readRDS(\"./data/processed/dtw_distance_ac_segments_200ms_schroeders.RDS\")\n\nmin_dists$dist <- scale(min_dists$dist)\n\ndist_tri <- PhenotypeSpace::rectangular_to_triangular(min_dists)\n\nfreq_bi_tri <- as.dist(binary_triangular_matrix(group = sapply(strsplit(rownames(dist_tri),\n    \"_\"), \"[[\", 2)))\n\ncomp_bi_tri <- as.dist(binary_triangular_matrix(group = gsub(\"_n|_p\",\n    \"\", sapply(strsplit(rownames(dist_tri), \"_\"), \"[[\", 3))))\n\nsign_bi_tri <- as.dist(binary_triangular_matrix(group = sapply(strsplit(rownames(dist_tri),\n    \"_\"), \"[[\", 4)))\n\nrect_var <- cbind(as.dist(dist_tri), freq_bi_tri, comp_bi_tri, sign_bi_tri)\n\ncolnames(rect_var) <- c(\"dtw_dist\", \"frequency\", \"components\", \"sign\")\n\nset.seed(123)\ndtw_wv_mod <- MRM2(formula = dtw_dist ~ frequency + components + sign,\n    nperm = 10000, mat = rect_var)\n\nsaveRDS(dtw_wv_mod, \"./data/processed/matrix_correlation_dtw_distance_200ms_schroeders.RDS\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .numberLines .lineAnchors .cell-code}\n(dtw_wv_mod <- readRDS(\"./data/processed/matrix_correlation_dtw_distance_200ms_schroeders.RDS\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$coef\n              dtw_dist   pval\nInt        -1.01906297 0.0001\nfrequency   0.97667642 0.0001\ncomponents  0.17603941 0.0001\nsign        0.02157794 0.0272\n\n$r.squared\n       R2      pval \n0.1151998 0.0001000 \n\n$F.test\n        F    F.pval \n1869.0880    0.0001 \n\n$n\n[1] 294\n```\n\n\n:::\n:::\n\n\n## Single Schroeder DTW\n\n- Using a single cycle of each Schroeder\n- Computed with `warbleR::waveform_similarity()`: amplitude vectors are normalized and resampled to 100 samples, one of them is duplicated and the other one is slid across the duplicated one (`type = \"sliding\"`)\n- The minimum DTW distance across sliding steps is kept as a dissimilarity measure\n- No band-pass filter is applied (`bp = NULL`)\n\n\n::: {.cell}\n\n```{.r .numberLines .lineAnchors .cell-code}\nschroeders <- readRDS(\"./data/processed/extended_selection_table_single_schroeders.RDS\")\n\nwv_sim <- waveform_similarity(X = schroeders, sim.method = \"DTW\",\n    type = \"sliding\", n = 100, bp = NULL, output = \"rectangular\")\n\n# remove selection number suffix ('-1') from IDs\nwv_sim <- data.frame(schr1 = gsub(\"-[0-9]+$\", \"\", wv_sim$id.1), schr2 = gsub(\"-[0-9]+$\",\n    \"\", wv_sim$id.2), dist = wv_sim$similarity)\n\nsaveRDS(wv_sim, \"./data/processed/dtw_distance_ac_segments_single_schroeders.RDS\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .numberLines .lineAnchors .cell-code}\nmin_dists <- readRDS(\"./data/processed/dtw_distance_ac_segments_single_schroeders.RDS\")\n\nmin_dists$dist <- scale(min_dists$dist)\n\ndist_tri <- PhenotypeSpace::rectangular_to_triangular(min_dists)\n\nfreq_bi_tri <- as.dist(binary_triangular_matrix(group = sapply(strsplit(rownames(dist_tri),\n    \"_\"), \"[[\", 2)))\n\ncomp_bi_tri <- as.dist(binary_triangular_matrix(group = gsub(\"_n|_p\",\n    \"\", sapply(strsplit(rownames(dist_tri), \"_\"), \"[[\", 3))))\n\nsign_bi_tri <- as.dist(binary_triangular_matrix(group = sapply(strsplit(rownames(dist_tri),\n    \"_\"), \"[[\", 4)))\n\nrect_var <- cbind(as.dist(dist_tri), freq_bi_tri, comp_bi_tri, sign_bi_tri)\n\ncolnames(rect_var) <- c(\"dtw_dist\", \"frequency\", \"components\", \"sign\")\n\nset.seed(123)\nsngl_dtw_wv_mod <- MRM2(formula = dtw_dist ~ frequency + components +\n    sign, nperm = 10000, mat = rect_var)\n\nsaveRDS(sngl_dtw_wv_mod, \"./data/processed/matrix_correlation_dtw_distance_single_schroeders.RDS\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .numberLines .lineAnchors .cell-code}\n(sngl_dtw_wv_mod <- readRDS(\"./data/processed/matrix_correlation_dtw_distance_single_schroeders.RDS\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$coef\n               dtw_dist   pval\nInt        -1.656790331 0.0001\nfrequency   0.003647731 0.7474\ncomponents  1.435963590 0.0001\nsign        0.560887982 0.0001\n\n$r.squared\n       R2      pval \n0.1634196 0.0001000 \n\n$F.test\n        F    F.pval \n2804.2704    0.0001 \n\n$n\n[1] 294\n```\n\n\n:::\n:::\n\n\n## Waveform correlation\n\n- Using waveforms of 200 ms with repeated Schroeder cycles\n- Computed with `warbleR::waveform_similarity()`: amplitude vectors are normalized and resampled to 100 samples, one of them is duplicated and the other one is slid across the duplicated one (`type = \"sliding\"`)\n- The maximum Pearson correlation across sliding steps is kept as a similarity measure\n- No band-pass filter is applied (`bp = NULL`)\n\n\n::: {.cell}\n\n```{.r .numberLines .lineAnchors .cell-code}\nschroeders <- readRDS(\"./data/processed/extended_selection_table_200ms_schroeders.RDS\")\n\nwv_sim <- waveform_similarity(X = schroeders, sim.method = \"correlation\",\n    type = \"sliding\", n = 100, bp = NULL, output = \"rectangular\")\n\n# remove selection number suffix ('-1') from IDs\nwv_sim <- data.frame(schr1 = gsub(\"-[0-9]+$\", \"\", wv_sim$id.1), schr2 = gsub(\"-[0-9]+$\",\n    \"\", wv_sim$id.2), cor = wv_sim$similarity)\n\nsaveRDS(wv_sim, \"./data/processed/waveform_correlation_200ms_schroeders.RDS\")\n```\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .numberLines .lineAnchors .cell-code}\ncors <- readRDS(\"./data/processed/waveform_correlation_200ms_schroeders.RDS\")\n\n# make it a distance\ncors$cor <- scale(1 - cors$cor)\n\ndist_tri <- PhenotypeSpace::rectangular_to_triangular(cors)\n\nfreq_bi_tri <- as.dist(binary_triangular_matrix(group = sapply(strsplit(rownames(dist_tri),\n    \"_\"), \"[[\", 2)))\n\ncomp_bi_tri <- as.dist(binary_triangular_matrix(group = gsub(\"_n|_p\",\n    \"\", sapply(strsplit(rownames(dist_tri), \"_\"), \"[[\", 3))))\n\nsign_bi_tri <- as.dist(binary_triangular_matrix(group = sapply(strsplit(rownames(dist_tri),\n    \"_\"), \"[[\", 4)))\n\nrect_var <- cbind(as.dist(dist_tri), freq_bi_tri, comp_bi_tri, sign_bi_tri)\n\ncolnames(rect_var) <- c(\"dtw_dist\", \"frequency\", \"components\", \"sign\")\n\nset.seed(123)\ncor_wv_mod <- MRM2(formula = dtw_dist ~ frequency + components + sign,\n    nperm = 10000, mat = rect_var)\n\nsaveRDS(cor_wv_mod, \"./data/processed/matrix_correlation_waveform_correlation_200ms_schroeders.RDS\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .numberLines .lineAnchors .cell-code}\n(cor_wv_mod <- readRDS(\"./data/processed/matrix_correlation_waveform_correlation_200ms_schroeders.RDS\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$coef\n              dtw_dist   pval\nInt        -1.49697967 0.0001\nfrequency   1.65973179 0.0001\ncomponents  0.01806886 0.3238\nsign        0.10410444 0.0001\n\n$r.squared\n       R2      pval \n0.3335816 0.0001000 \n\n$F.test\n        F    F.pval \n7185.8562    0.0001 \n\n$n\n[1] 294\n```\n\n\n:::\n:::\n\n\n## Single schroeder correlation\n\n- Using a single cycle of each Schroeder\n- Computed with `warbleR::waveform_similarity()`: amplitude vectors are normalized and resampled to 100 samples, one of them is duplicated and the other one is slid across the duplicated one (`type = \"sliding\"`)\n- The maximum Pearson correlation across sliding steps is kept as a similarity measure\n- No band-pass filter is applied (`bp = NULL`)\n\n\n::: {.cell}\n\n```{.r .numberLines .lineAnchors .cell-code}\nschroeders <- readRDS(\"./data/processed/extended_selection_table_single_schroeders.RDS\")\n\nwv_sim <- waveform_similarity(X = schroeders, sim.method = \"correlation\",\n    type = \"sliding\", n = 100, bp = NULL, output = \"rectangular\")\n\n# remove selection number suffix ('-1') from IDs\nwv_sim <- data.frame(schr1 = gsub(\"-[0-9]+$\", \"\", wv_sim$id.1), schr2 = gsub(\"-[0-9]+$\",\n    \"\", wv_sim$id.2), cor = wv_sim$similarity)\n\nsaveRDS(wv_sim, \"./data/processed/waveform_correlation_single_schroeders.RDS\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .numberLines .lineAnchors .cell-code}\ncors <- readRDS(\"./data/processed/waveform_correlation_single_schroeders.RDS\")\n\n# make it a distance\ncors$cor <- scale(1 - cors$cor)\n\ndist_tri <- PhenotypeSpace::rectangular_to_triangular(cors)\n\nfreq_bi_tri <- as.dist(binary_triangular_matrix(group = sapply(strsplit(rownames(dist_tri),\n    \"_\"), \"[[\", 2)))\n\ncomp_bi_tri <- as.dist(binary_triangular_matrix(group = gsub(\"_n|_p\",\n    \"\", sapply(strsplit(rownames(dist_tri), \"_\"), \"[[\", 3))))\n\nsign_bi_tri <- as.dist(binary_triangular_matrix(group = sapply(strsplit(rownames(dist_tri),\n    \"_\"), \"[[\", 4)))\n\nrect_var <- cbind(as.dist(dist_tri), freq_bi_tri, comp_bi_tri, sign_bi_tri)\n\ncolnames(rect_var) <- c(\"dtw_dist\", \"frequency\", \"components\", \"sign\")\n\nset.seed(123)\nsngl_cor_wv_mod <- MRM2(formula = dtw_dist ~ frequency + components +\n    sign, nperm = 10000, mat = rect_var)\n\nsaveRDS(sngl_cor_wv_mod, \"./data/processed/matrix_correlation_waveform_correlation_single_schroeders.RDS\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .numberLines .lineAnchors .cell-code}\n(sngl_cor_wv_mod <- readRDS(\"./data/processed/matrix_correlation_waveform_correlation_single_schroeders.RDS\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$coef\n             dtw_dist   pval\nInt        -1.7867059 0.0001\nfrequency  -0.0361176 0.0038\ncomponents  1.4893583 0.0001\nsign        0.7863002 0.0001\n\n$r.squared\n       R2      pval \n0.2453437 0.0001000 \n\n$F.test\n        F    F.pval \n4667.1216    0.0001 \n\n$n\n[1] 294\n```\n\n\n:::\n:::\n\n\n## Raven's spectrographic features\n\n::: {.cell}\n\n```{.r .numberLines .lineAnchors .cell-code}\nrav_dat <- imp_raven(path = \"./data/processed\", files = \"200ms_schroeders.txt\",\n    warbler.format = TRUE, all.data = TRUE)\n\nrav_dat <- rav_dat[grep(pattern = \"marker\", rav_dat$sound.id, invert = TRUE),\n    ]\n\nrav_dat <- rav_dat[, grep(\"contour|PFC Slope\", ignore.case = TRUE,\n    x = names(rav_dat), invert = TRUE)]\n\npca <- prcomp(x = rav_dat[, names(rav_dat) %in% c(\"Agg Entropy (bits)\",\n    \"Avg Entropy (bits)\", \"Avg Power Density (dB FS/Hz)\", \"BW 50% (Hz)\",\n    \"BW 90% (Hz)\", \"Center Freq (Hz)\", \"Center Time Rel.\", \"Delta Freq (Hz)\",\n    \"Dur 50% (s)\", \"Dur 90% (s)\", \"Energy (dB FS)\", \"Freq 25% (Hz)\",\n    \"Freq 5% (Hz)\", \"Freq 75% (Hz)\", \"Freq 95% (Hz)\", \"Inband Power (dB FS)\",\n    \"Max Entropy (bits)\", \"Max Freq (Hz)\", \"Min Entropy (bits)\", \"Peak Freq (Hz)\",\n    \"PFC Avg Slope (Hz/ms)\", \"PFC Max Freq (Hz)\", \"PFC Max Slope (Hz/ms)\",\n    \"PFC Min Freq (Hz)\", \"PFC Min Slope (Hz/ms)\", \"PFC Num Inf Pts\",\n    \"Peak Power Density (dB FS/Hz)\", \"Peak Time (s)\", \"Peak Time Relative\",\n    \"Time 25% (s)\", \"Time 25% Rel.\", \"Time 5% (s)\", \"Time 5% Rel.\",\n    \"Time 75% (s)\", \"Time 75% Rel.\", \"Time 95% (s)\", \"Time 95% Rel.\")],\n    scale. = TRUE)\n\nrav_dat$pc1 <- pca$x[, 1]\nrav_dat$pc2 <- pca$x[, 2]\nrav_dat$comp <- sapply(strsplit(rav_dat$label, \"_\"), \"[[\", 1)\nrav_dat$sign <- sapply(strsplit(rav_dat$label, \"_\"), \"[[\", 2)\nrav_dat$label <- paste(rav_dat$f0, rav_dat$label, sep = \"-\")\n\ndist_tri <- dist(rav_dat[, c(\"pc1\", \"pc2\")])\n\nfreq_bi_tri <- as.dist(binary_triangular_matrix(group = rav_dat$f0))\n\ncomp_bi_tri <- as.dist(binary_triangular_matrix(group = rav_dat$comp))\n\nsign_bi_tri <- as.dist(binary_triangular_matrix(group = rav_dat$sign))\n\nrect_var <- cbind(as.dist(scale(as.matrix(dist_tri))), freq_bi_tri,\n    comp_bi_tri, sign_bi_tri)\n\ncolnames(rect_var) <- c(\"rav_dist\", \"frequency\", \"components\", \"sign\")\n\n\nset.seed(123)\nrav_mod <- MRM2(formula = rav_dist ~ frequency + components + sign,\n    nperm = 10000, mat = rect_var)\n\nsaveRDS(rav_mod, \"./data/processed/matrix_correlation_raven_measurements_distance_200ms_schroeders.RDS\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .numberLines .lineAnchors .cell-code}\n(rav_mod <- readRDS(\"./data/processed/matrix_correlation_raven_measurements_distance_200ms_schroeders.RDS\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$coef\n               rav_dist   pval\nInt        -1.313691913 0.0001\nfrequency   0.884850197 0.0001\ncomponents  0.656905001 0.0001\nsign       -0.004730867 0.5454\n\n$r.squared\n       R2      pval \n0.1007162 0.0001000 \n\n$F.test\n        F    F.pval \n1607.7775    0.0001 \n\n$n\n[1] 294\n```\n\n\n:::\n:::\n\n\n## warbleR's spectrographic features\n\nMeasure spectrographic features:\n\n::: {.cell}\n\n```{.r .numberLines .lineAnchors .cell-code}\nest_schr <- readRDS(\"./data/processed/extended_selection_table_200ms_schroeders.RDS\")\n\nwsp <- spectro_analysis(est_schr, harmonicity = TRUE, nharmonics = 5,\n    parallel = 20)\n\nsaveRDS(wsp, \"./data/processed/warbler_spectrographic_features_200ms_schroeders.RDS\")\n```\n:::\n\n\nStatistical model:\n\n::: {.cell}\n\n```{.r .numberLines .lineAnchors .cell-code}\nwsp <- readRDS(\"./data/processed/warbler_spectrographic_features_200ms_schroeders.RDS\")\n\n# keep columns with no NAs\nwsp <- wsp[complete.cases(wsp), ]\n\npca <- prcomp(x = wsp[, -c(1:3)])\nwsp$pc1 <- pca$x[, 1]\nwsp$pc2 <- pca$x[, 2]\n\nwsp_tri <- dist(wsp[, c(\"pc1\", \"pc2\")])\n\nfreq_bi_tri <- as.dist(binary_triangular_matrix(group = substr(sapply(strsplit(wsp$sound.files,\n    \"_\"), \"[[\", 2), start = 4, 6)))\n\ncomp_bi_tri <- as.dist(binary_triangular_matrix(group = substr(sapply(strsplit(wsp$sound.files,\n    \"_\"), \"[[\", 3), start = 7, 8)))\n\nsign_bi_tri <- as.dist(binary_triangular_matrix(group = ifelse(grepl(\"pos\",\n    wsp$sound.files), \"pos\", \"neg\")))\n\nrect_var <- cbind(as.dist(scale(as.matrix(wsp_tri))), freq_bi_tri,\n    comp_bi_tri, sign_bi_tri)\n\ncolnames(rect_var) <- c(\"wrbl_sp\", \"frequency\", \"components\", \"sign\")\n\nset.seed(123)\nwrbl_mod <- MRM2(formula = wrbl_sp ~ frequency + components + sign,\n    nperm = 10000, mat = rect_var)\n\nsaveRDS(wrbl_mod, \"./data/processed/matrix_correlation_warbler_measurements_distance_200ms_schroeder.RDS\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .numberLines .lineAnchors .cell-code}\n(wrbl_mod <- readRDS(\"./data/processed/matrix_correlation_warbler_measurements_distance_200ms_schroeder.RDS\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$coef\n                wrbl_sp   pval\nInt        -0.868887055 0.0001\nfrequency   1.014984061 0.0001\ncomponents  0.057791772 0.0050\nsign        0.001089815 0.8880\n\n$r.squared\n      R2     pval \n0.109935 0.000100 \n\n$F.test\n        F    F.pval \n1773.1184    0.0001 \n\n$n\n[1] 294\n```\n\n\n:::\n:::\n\n\n## warbleR's MFCC features\n\nMeasure MFCC descriptors:\n\n::: {.cell}\n\n```{.r .numberLines .lineAnchors .cell-code}\nest_schr <- readRDS(\"./data/processed/extended_selection_table_200ms_schroeders.RDS\")\n\nwsp <- mfcc_stats(est_schr)\n\nsaveRDS(wsp, \"./data/processed/warbler_mfcc_descriptors_200ms_schroeders.RDS\")\n```\n:::\n\n\nStatistical model:\n\n::: {.cell}\n\n```{.r .numberLines .lineAnchors .cell-code}\nwsp <- readRDS(\"./data/processed/warbler_mfcc_descriptors_200ms_schroeders.RDS\")\n\n# keep columns with no NAs\nwsp <- wsp[complete.cases(wsp), ]\n\npca <- prcomp(x = wsp[, -c(1:3)])\nwsp$pc1 <- pca$x[, 1]\nwsp$pc2 <- pca$x[, 2]\n\nwsp_tri <- dist(wsp[, c(\"pc1\", \"pc2\")])\n\nfreq_bi_tri <- as.dist(binary_triangular_matrix(group = substr(sapply(strsplit(wsp$sound.files,\n    \"_\"), \"[[\", 2), start = 4, 6)))\n\ncomp_bi_tri <- as.dist(binary_triangular_matrix(group = substr(sapply(strsplit(wsp$sound.files,\n    \"_\"), \"[[\", 3), start = 7, 8)))\n\nsign_bi_tri <- as.dist(binary_triangular_matrix(group = ifelse(grepl(\"pos\",\n    wsp$sound.files), \"pos\", \"neg\")))\n\nrect_var <- cbind(as.dist(scale(as.matrix(wsp_tri))), freq_bi_tri,\n    comp_bi_tri, sign_bi_tri)\n\ncolnames(rect_var) <- c(\"wrbl_sp\", \"frequency\", \"components\", \"sign\")\n\nset.seed(123)\nmfcc_wrbl_mod <- MRM2(formula = wrbl_sp ~ frequency + components +\n    sign, nperm = 10000, mat = rect_var)\n\nsaveRDS(mfcc_wrbl_mod, \"./data/processed/mfcc_warbler_distance_200ms_schroeders.RDS\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .numberLines .lineAnchors .cell-code}\n(mfcc_wrbl_mod <- readRDS(\"./data/processed/mfcc_warbler_distance_200ms_schroeders.RDS\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$coef\n                wrbl_sp   pval\nInt        -0.975754366 0.0001\nfrequency   1.079864077 0.0001\ncomponents  0.076157199 0.0010\nsign       -0.003342104 0.6652\n\n$r.squared\n       R2      pval \n0.1363803 0.0001000 \n\n$F.test\n        F    F.pval \n2267.0058    0.0001 \n\n$n\n[1] 294\n```\n\n\n:::\n:::\n\n\n## warbleR's fourier cross-correlation\n\n::: {.cell}\n\n```{.r .numberLines .lineAnchors .cell-code}\nest_schr <- readRDS(\"./data/processed/extended_selection_table_200ms_schroeders.RDS\")\n\n# mimicking raven\nxc <- cross_correlation(est_schr, ovlp = 50, parallel = 20, wl = 512,\n    bp = c(0, 22), wn = \"hamming\")\n\nsaveRDS(xc, \"./data/processed/fourier_cross_correlation_200ms_schroeders.RDS\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .numberLines .lineAnchors .cell-code}\nxc <- readRDS(\"./data/processed/fourier_cross_correlation_200ms_schroeders.RDS\")\n\nfreq_bi_tri <- as.dist(binary_triangular_matrix(group = substr(sapply(strsplit(rownames(xc),\n    \"_\"), \"[[\", 2), start = 4, 6)))\n\ncomp_bi_tri <- as.dist(binary_triangular_matrix(group = substr(sapply(strsplit(rownames(xc),\n    \"_\"), \"[[\", 3), start = 7, 8)))\n\nsign_bi_tri <- as.dist(binary_triangular_matrix(group = ifelse(grepl(\"pos\",\n    rownames(xc)), \"pos\", \"neg\")))\n\nrect_var <- cbind(as.dist(scale(1 - xc)), freq_bi_tri, comp_bi_tri,\n    sign_bi_tri)\n\ncolnames(rect_var) <- c(\"fourier_xc\", \"frequency\", \"components\", \"sign\")\n\nset.seed(123)\nxc_mod <- MRM2(formula = fourier_xc ~ frequency + components + sign,\n    nperm = 10000, mat = rect_var)\n\nsaveRDS(xc_mod, \"./data/processed/matrix_correlation_fourier_cross_correlation_200ms_schroeders.RDS\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .numberLines .lineAnchors .cell-code}\n(xc_mod <- readRDS(\"./data/processed/matrix_correlation_fourier_cross_correlation_200ms_schroeders.RDS\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$coef\n            fourier_xc   pval\nInt        -1.26349363 0.0001\nfrequency   1.47923044 0.0001\ncomponents  0.18508315 0.0001\nsign       -0.00105614 0.8878\n\n$r.squared\n       R2      pval \n0.2273505 0.0001000 \n\n$F.test\n        F    F.pval \n4224.1242    0.0001 \n\n$n\n[1] 294\n```\n\n\n:::\n:::\n\n\n## Raven's fourier cross-correlation\n\n- Hamming window function\n- 512 samples FFT\n- Un-normalized\n- bandpass 0-22 kHz\n\n\n\n::: {.cell}\n\n```{.r .numberLines .lineAnchors .cell-code}\nxc_rav <- Rraven::imp_corr_mat(file = \"BatchCorrOutput_v3_hamming.txt\",\n    path = \"./data/processed\")[[1]]\n\nfreq_bi_tri <- as.dist(binary_triangular_matrix(group = substr(sapply(strsplit(rownames(xc_rav),\n    \"_\"), \"[[\", 2), start = 4, 6)))\n\ncomp_bi_tri <- as.dist(binary_triangular_matrix(group = substr(sapply(strsplit(rownames(xc_rav),\n    \"_\"), \"[[\", 3), start = 7, 8)))\n\nsign_bi_tri <- as.dist(binary_triangular_matrix(group = ifelse(grepl(\"pos\",\n    rownames(xc_rav)), \"pos\", \"neg\")))\n\nrect_var <- cbind(as.dist(scale(1 - xc_rav)), freq_bi_tri, comp_bi_tri,\n    sign_bi_tri)\n\ncolnames(rect_var) <- c(\"fourier_xc_rav\", \"frequency\", \"components\",\n    \"sign\")\n\nset.seed(123)\nxc_rav_mod <- MRM2(formula = fourier_xc_rav ~ frequency + components +\n    sign, nperm = 10000, mat = rect_var)\n\nsaveRDS(xc_rav_mod, \"./data/processed/matrix_correlation_raven_fourier_cross_correlation_200ms_schroeders.RDS\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .numberLines .lineAnchors .cell-code}\n(xc_rav_mod <- readRDS(\"./data/processed/matrix_correlation_raven_fourier_cross_correlation_200ms_schroeders.RDS\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$coef\n           fourier_xc_rav   pval\nInt          -2.014130558 0.0001\nfrequency     2.231893880 0.0001\ncomponents    0.113853680 0.0001\nsign         -0.005230222 0.3246\n\n$r.squared\n      R2     pval \n0.610634 0.000100 \n\n$F.test\n         F     F.pval \n22513.6725     0.0001 \n\n$n\n[1] 294\n```\n\n\n:::\n:::\n\n\n## Raven's waveform correlation\n\n::: {.cell}\n\n```{.r .numberLines .lineAnchors .cell-code}\nwav_cr_rav <- Rraven::imp_corr_mat(file = \"raven_waveform_correlation_200ms_schroeders.txt\",\n    path = \"./data/processed\")[[1]]\n\nfreq_bi_tri <- as.dist(binary_triangular_matrix(group = substr(sapply(strsplit(rownames(wav_cr_rav),\n    \"_\"), \"[[\", 2), start = 4, 6)))\n\ncomp_bi_tri <- as.dist(binary_triangular_matrix(group = substr(sapply(strsplit(rownames(wav_cr_rav),\n    \"_\"), \"[[\", 3), start = 7, 8)))\n\nsign_bi_tri <- as.dist(binary_triangular_matrix(group = ifelse(grepl(\"pos\",\n    rownames(wav_cr_rav)), \"pos\", \"neg\")))\n\nrect_var <- cbind(as.dist(scale(1 - wav_cr_rav)), freq_bi_tri, comp_bi_tri,\n    sign_bi_tri)\n\ncolnames(rect_var) <- c(\"fourier_wav_cr_rav\", \"frequency\", \"components\",\n    \"sign\")\n\nset.seed(123)\nwav_cr_rav_mod <- MRM2(formula = fourier_wav_cr_rav ~ frequency +\n    components + sign, nperm = 10000, mat = rect_var)\n\nsaveRDS(wav_cr_rav_mod, \"./data/processed/matrix_correlation_raven_waveform_correlation_200ms_schroeders.RDS\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .numberLines .lineAnchors .cell-code}\n(wav_cr_rav_mod <- readRDS(\"./data/processed/matrix_correlation_raven_waveform_correlation_200ms_schroeders.RDS\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$coef\n           fourier_wav_cr_rav  pval\nInt               -1.70648537 1e-04\nfrequency          1.89485351 1e-04\ncomponents         0.04435588 5e-03\nsign               0.11919270 1e-04\n\n$r.squared\n       R2      pval \n0.4988993 0.0001000 \n\n$F.test\n         F     F.pval \n14292.5996     0.0001 \n\n$n\n[1] 294\n```\n\n\n:::\n:::\n\n\n## warbleR's mel-frequency cross-correlation\n\n::: {.cell}\n\n```{.r .numberLines .lineAnchors .cell-code}\nest_schr <- readRDS(\"./data/processed/extended_selection_table_200ms_schroeders.RDS\")\n\nxc <- cross_correlation(est_schr, type = \"mfcc\")\n\nsaveRDS(xc, \"./data/processed/mel_frequency_cross_correlation_200ms_schroeders.RDS\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .numberLines .lineAnchors .cell-code}\nxc <- readRDS(\"./data/processed/mel_frequency_cross_correlation_200ms_schroeders.RDS\")\n\nfreq_bi_tri <- as.dist(binary_triangular_matrix(group = substr(sapply(strsplit(rownames(xc),\n    \"_\"), \"[[\", 2), start = 4, 6)))\n\ncomp_bi_tri <- as.dist(binary_triangular_matrix(group = substr(sapply(strsplit(rownames(xc),\n    \"_\"), \"[[\", 3), start = 7, 8)))\n\nsign_bi_tri <- as.dist(binary_triangular_matrix(group = ifelse(grepl(\"pos\",\n    rownames(xc)), \"pos\", \"neg\")))\n\nrect_var <- cbind(as.dist(scale(1 - xc)), freq_bi_tri, comp_bi_tri,\n    sign_bi_tri)\n\n\ncolnames(rect_var) <- c(\"mel_xc\", \"frequency\", \"components\", \"sign\")\n\n\nset.seed(123)\nmxc_mod <- MRM2(formula = mel_xc ~ frequency + components + sign,\n    nperm = 10000, mat = rect_var)\n\nsaveRDS(mxc_mod, \"./data/processed/matrix_correlation_mel_cross_correlation_200ms_schroeders.RDS\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .numberLines .lineAnchors .cell-code}\n(mxc_mod <- readRDS(\"./data/processed/matrix_correlation_mel_cross_correlation_200ms_schroeders.RDS\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$coef\n                 mel_xc   pval\nInt        -1.262642488 0.0001\nfrequency   1.256694806 0.0001\ncomponents  0.248868505 0.0001\nsign        0.002007171 0.7868\n\n$r.squared\n       R2      pval \n0.1796265 0.0001000 \n\n$F.test\n        F    F.pval \n3143.2731    0.0001 \n\n$n\n[1] 294\n```\n\n\n:::\n:::\n\n\n## SAP harmonic goodness\n\n- SAP: sound analysis pro\n- This analysis was done on 200 ms clips as longer clips did not run in SAP\n\n\n::: {.cell}\n\n```{.r .numberLines .lineAnchors .cell-code}\nsimil_sap <- readxl::read_xlsx(\"./data/raw/200ms_SAPsim.xlsx\")\n\n\n# number of pairwise comparisons posibles\nclips <- unique(c(simil_sap$`Sound 1`, simil_sap$`Sound 2`))\n\nncol(poss_combs <- combn(clips, 2))\n\nposs_combs <- t(poss_combs)\n\nposs_dyad <- sapply(seq_len(nrow(poss_combs)), function(x) {\n    paste(sort(c(poss_combs[x, 1], poss_combs[x, 2])), collapse = \"|\")\n})\n\n\nsimil_sap$dyad <- sapply(seq_len(nrow(simil_sap)), function(x) {\n    paste(sort(c(simil_sap$`Sound 1`[x], simil_sap$`Sound 2`[x])),\n        collapse = \"|\")\n})\n\n# remove duplicated dyads\nsimil_sap <- simil_sap[!duplicated(simil_sap$dyad), ]\n\n# remove self comparisons\nsimil_sap <- simil_sap[!simil_sap$`Sound 1` == simil_sap$`Sound 2`,\n    ]\n\nnrow(simil_sap)\n\n# missing dyads\nmissing <- poss_dyad[!poss_dyad %in% simil_sap$dyad]\n\n# split missing by |\nmissing <- unique(c(sapply(strsplit(missing, \"|\", fixed = TRUE), \"[[\",\n    1), sapply(strsplit(missing, \"|\", fixed = TRUE), \"[[\", 2)))\n\n# remove missing clips\nsimil_sap <- simil_sap[!(simil_sap$`Sound 1` %in% missing | simil_sap$`Sound 2` %in%\n    missing), ]\n\n# convert to distance\nsimil_sap$`Goodness diff` <- simil_sap$`Goodness diff` * -1\n\n# get symmetric triangular matrix\ndist_sap <- rectangular_to_triangular(as.data.frame(simil_sap[, c(\"Sound 1\",\n    \"Sound 2\", \"Goodness diff\")]))\n\nfreq_bi_tri <- as.dist(binary_triangular_matrix(group = substr(sapply(strsplit(rownames(dist_sap),\n    \"_\"), \"[[\", 2), start = 4, 6)))\n\ncomp_bi_tri <- as.dist(binary_triangular_matrix(group = substr(sapply(strsplit(rownames(dist_sap),\n    \"_\"), \"[[\", 3), start = 7, 8)))\n\nsign_bi_tri <- as.dist(binary_triangular_matrix(group = ifelse(grepl(\"pos\",\n    rownames(dist_sap)), \"pos\", \"neg\")))\n\nrect_var <- cbind(as.dist(scale(1 - dist_sap)), freq_bi_tri, comp_bi_tri,\n    sign_bi_tri)\n\ncolnames(rect_var) <- c(\"dist_sap\", \"frequency\", \"components\", \"sign\")\n\nrect_var[is.na(rect_var[, 1]), 1] <- mean(rect_var[, 1], na.rm = TRUE)\n\nset.seed(123)\ngood_sap_mod <- MRM2(formula = dist_sap ~ frequency + components +\n    sign, nperm = 10000, mat = rect_var)\n\nsaveRDS(good_sap_mod, \"./data/processed/matrix_correlation_sound_analysis_pro_goodness_200_ms_clips.RDS\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .numberLines .lineAnchors .cell-code}\n(good_sap_mod <- readRDS(\"./data/processed/matrix_correlation_sound_analysis_pro_goodness_200_ms_clips.RDS\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$coef\n               dist_sap   pval\nInt        -0.711874155 0.0001\nfrequency   1.182727718 0.0001\ncomponents -0.009919279 0.6020\nsign       -0.000160463 0.9863\n\n$r.squared\n       R2      pval \n0.1197922 0.0001000 \n\n$F.test\n        F    F.pval \n1953.7405    0.0001 \n\n$n\n[1] 294\n```\n\n\n:::\n:::\n\n\n\n## SAP pitch difference\n\n- SAP: sound analysis pro\n- This analysis was done on 200 ms clips as longer clips did not run in SAP\n\n\n::: {.cell}\n\n```{.r .numberLines .lineAnchors .cell-code}\nsimil_sap <- readxl::read_xlsx(\"./data/raw/200ms_SAPsim.xlsx\")\n\n# number of pairwise comparisons posibles\nclips <- unique(c(simil_sap$`Sound 1`, simil_sap$`Sound 2`))\n\nncol(poss_combs <- combn(clips, 2))\n\nposs_combs <- t(poss_combs)\n\nposs_dyad <- sapply(seq_len(nrow(poss_combs)), function(x) {\n    paste(sort(c(poss_combs[x, 1], poss_combs[x, 2])), collapse = \"|\")\n})\n\n\nsimil_sap$dyad <- sapply(seq_len(nrow(simil_sap)), function(x) {\n    paste(sort(c(simil_sap$`Sound 1`[x], simil_sap$`Sound 2`[x])),\n        collapse = \"|\")\n})\n\n# remove duplicated dyads\nsimil_sap <- simil_sap[!duplicated(simil_sap$dyad), ]\n\n# remove self comparisons\nsimil_sap <- simil_sap[!simil_sap$`Sound 1` == simil_sap$`Sound 2`,\n    ]\n\nnrow(simil_sap)\n\n# missing dyads\nmissing <- poss_dyad[!poss_dyad %in% simil_sap$dyad]\n\n# split missing by |\nmissing <- unique(c(sapply(strsplit(missing, \"|\", fixed = TRUE), \"[[\",\n    1), sapply(strsplit(missing, \"|\", fixed = TRUE), \"[[\", 2)))\n\n# remove missing clips\nsimil_sap <- simil_sap[!(simil_sap$`Sound 1` %in% missing | simil_sap$`Sound 2` %in%\n    missing), ]\n\n# convert to distance\nsimil_sap$`Pitch diff` <- simil_sap$`Pitch diff` * -1\n\n\n# get symmetric triangular matrix\ndist_sap <- rectangular_to_triangular(as.data.frame(simil_sap[, c(\"Sound 1\",\n    \"Sound 2\", \"Pitch diff\")]))\n\nfreq_bi_tri <- as.dist(binary_triangular_matrix(group = substr(sapply(strsplit(rownames(dist_sap),\n    \"_\"), \"[[\", 2), start = 4, 6)))\n\ncomp_bi_tri <- as.dist(binary_triangular_matrix(group = substr(sapply(strsplit(rownames(dist_sap),\n    \"_\"), \"[[\", 3), start = 7, 8)))\n\nsign_bi_tri <- as.dist(binary_triangular_matrix(group = ifelse(grepl(\"pos\",\n    rownames(dist_sap)), \"pos\", \"neg\")))\n\nrect_var <- cbind(as.dist(scale(1 - dist_sap)), freq_bi_tri, comp_bi_tri,\n    sign_bi_tri)\n\ncolnames(rect_var) <- c(\"dist_sap\", \"frequency\", \"components\", \"sign\")\n\nrect_var[is.na(rect_var[, 1]), 1] <- mean(rect_var[, 1], na.rm = TRUE)\n\nset.seed(123)\npitch_diff_mod <- MRM2(formula = dist_sap ~ frequency + components +\n    sign, nperm = 10000, mat = rect_var)\n\nsaveRDS(pitch_diff_mod, \"./data/processed/matrix_correlation_sound_analysis_pro_pitch_diff_200_ms_clips.RDS\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .numberLines .lineAnchors .cell-code}\n(pitch_diff_mod <- readRDS(\"./data/processed/matrix_correlation_sound_analysis_pro_pitch_diff_200_ms_clips.RDS\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$coef\n              dist_sap   pval\nInt        -0.26814278 0.0001\nfrequency   0.12204666 0.0001\ncomponents  0.10396671 0.0001\nsign        0.01128282 0.0829\n\n$r.squared\n         R2        pval \n0.003378295 0.000100000 \n\n$F.test\n       F   F.pval \n48.66207  0.00010 \n\n$n\n[1] 294\n```\n\n\n:::\n:::\n\n\n## SAP amplitude modulation\n\n- SAP: sound analysis pro\n- This analysis was done on 200 ms clips as longer clips did not run in SAP\n\n\n::: {.cell}\n\n```{.r .numberLines .lineAnchors .cell-code}\nsimil_sap <- readxl::read_xlsx(\"./data/raw/200ms_SAPsim.xlsx\")\n\n# number of pairwise comparisons posibles\nclips <- unique(c(simil_sap$`Sound 1`, simil_sap$`Sound 2`))\n\nncol(poss_combs <- combn(clips, 2))\n\nposs_combs <- t(poss_combs)\n\nposs_dyad <- sapply(seq_len(nrow(poss_combs)), function(x) {\n    paste(sort(c(poss_combs[x, 1], poss_combs[x, 2])), collapse = \"|\")\n})\n\n\nsimil_sap$dyad <- sapply(seq_len(nrow(simil_sap)), function(x) {\n    paste(sort(c(simil_sap$`Sound 1`[x], simil_sap$`Sound 2`[x])),\n        collapse = \"|\")\n})\n\n# remove duplicated dyads\nsimil_sap <- simil_sap[!duplicated(simil_sap$dyad), ]\n\n# remove self comparisons\nsimil_sap <- simil_sap[!simil_sap$`Sound 1` == simil_sap$`Sound 2`,\n    ]\n\nnrow(simil_sap)\n\n# missing dyads\nmissing <- poss_dyad[!poss_dyad %in% simil_sap$dyad]\n\n# split missing by |\nmissing <- unique(c(sapply(strsplit(missing, \"|\", fixed = TRUE), \"[[\",\n    1), sapply(strsplit(missing, \"|\", fixed = TRUE), \"[[\", 2)))\n\n# remove missing clips\nsimil_sap <- simil_sap[!(simil_sap$`Sound 1` %in% missing | simil_sap$`Sound 2` %in%\n    missing), ]\n\n# get symmetric triangular matrix\ndist_sap <- rectangular_to_triangular(as.data.frame(simil_sap[, c(\"Sound 1\",\n    \"Sound 2\", \"AM diff\")]))\n\nfreq_bi_tri <- as.dist(binary_triangular_matrix(group = substr(sapply(strsplit(rownames(dist_sap),\n    \"_\"), \"[[\", 2), start = 4, 6)))\n\ncomp_bi_tri <- as.dist(binary_triangular_matrix(group = substr(sapply(strsplit(rownames(dist_sap),\n    \"_\"), \"[[\", 3), start = 7, 8)))\n\nsign_bi_tri <- as.dist(binary_triangular_matrix(group = ifelse(grepl(\"pos\",\n    rownames(dist_sap)), \"pos\", \"neg\")))\n\nrect_var <- cbind(as.dist(scale(1 - dist_sap)), freq_bi_tri, comp_bi_tri,\n    sign_bi_tri)\n\ncolnames(rect_var) <- c(\"dist_sap\", \"frequency\", \"components\", \"sign\")\n\nrect_var[is.na(rect_var[, 1]), 1] <- mean(rect_var[, 1], na.rm = TRUE)\n\nset.seed(123)\nam_sap_mod <- MRM2(formula = dist_sap ~ frequency + components + sign,\n    nperm = 10000, mat = rect_var)\n\nsaveRDS(am_sap_mod, \"./data/processed/matrix_correlation_sound_analysis_pro_amplitude_modulation_200_ms_clips.RDS\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .numberLines .lineAnchors .cell-code}\n(am_sap_mod <- readRDS(\"./data/processed/matrix_correlation_sound_analysis_pro_amplitude_modulation_200_ms_clips.RDS\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$coef\n                dist_sap   pval\nInt        -0.0239282366 0.2762\nfrequency   0.0160426132 0.0123\ncomponents -0.0075928468 0.4679\nsign        0.0008302052 0.8086\n\n$r.squared\n          R2         pval \n3.116584e-05 6.900000e-02 \n\n$F.test\n        F    F.pval \n0.4474203 0.0690000 \n\n$n\n[1] 294\n```\n\n\n:::\n:::\n\n\n\n## Combined results (Fig. 6)\n\n::: {.cell}\n\n```{.r .numberLines .lineAnchors .cell-code}\nmods <- list(`waveform DTW (wblR, rep)` = dtw_wv_mod, `waveform DTW (wblR, sngl)` = sngl_dtw_wv_mod,\n    `waveform correlation (wblR, rep)` = cor_wv_mod, `waveform correlation (wblR, sngl)` = sngl_cor_wv_mod,\n    `spectro-temporal features (wblR)` = wrbl_mod, `MFCC descriptors (wblR)` = mfcc_wrbl_mod,\n    `spectro-temporal features (Rvn)` = rav_mod, `linear freq. cross-correlation (wblR)` = xc_mod,\n    `mel freq. cross-correlation (wblR)` = mxc_mod, `waveform correlation (Rvn, rep)` = wav_cr_rav_mod,\n    `linear freq. cross-correlation (Rvn)` = xc_rav_mod, `harmonic goodness (SAP)` = good_sap_mod,\n    `pitch differences (SAP)` = pitch_diff_mod, `amplitude modulation (SAP)` = am_sap_mod)\n\n\nestimates <- do.call(rbind, lapply(seq_along(mods), function(x) {\n    Y <- data.frame(mods[[x]]$coef[-1, ])\n    Y$rel_coef <- Y[, 1]/max(Y[, 1])\n    Y$mod <- names(mods)[x]\n    Y$predictor <- rownames(Y)\n    names(Y) <- c(\"coef\", \"p\", \"rel_coef\", \"model\", \"predictor\")\n    return(Y)\n}))\n\nestimates$rel_coef <- ifelse(estimates$p < 0.05, estimates$rel_coef,\n    0)\nestimates$signif <- ifelse(estimates$p < 0.05, \"p < 0.05\", \"p >= 0.05\")\n\n# sort factor level by rel_coef\nestimates$model <- factor(estimates$model, levels = estimates$model[estimates$predictor ==\n    \"sign\"][order(estimates$coef[estimates$predictor == \"sign\"], decreasing = TRUE)])\n\nestimates$predictor <- gsub(\"sign\", \"Phase\", estimates$predictor)\nestimates$predictor <- levels(factor(estimates$predictor, levels = c(\"Frequency\",\n    \"Harmonics\", \"Phase\")))\n\n\ngg_effects <- ggplot(estimates, aes(x = predictor, y = model, fill = coef)) +\n    geom_tile() + coord_equal() + scale_fill_gradient2(low = mako(10)[3],\n    high = mako(10)[7], guide = \"none\") + geom_text(aes(label = round(coef,\n    3), color = signif), size = 4) + scale_color_manual(values = c(\"black\",\n    \"gray\")) + labs(x = \"\", y = \"\", color = \"P value\") + theme_classic() +\n    theme(axis.text.x = element_text(color = \"black\", size = 12, angle = 45,\n        vjust = 0.95, hjust = 0.9), axis.text.y = element_text(color = \"black\",\n        size = 13))\n\ngg_effects <- gg_effects + coord_flip()\n\nggsave(filename = \"./output/figures/fig6_effect_sizes_by_method.png\",\n    plot = gg_effects, width = 10, height = 5, dpi = 300, units = \"in\")\n```\n:::\n\n\n![Effect sizes (cell values) by predictor and acoustic analysis method. Font color shows statistical significance (black p < 0.05, gray p >= 0.05)](../output/figures/fig6_effect_sizes_by_method.png){#fig-effect-sizes}\n\n<div class=\"alert alert-success\">\n\n&nbsp; \n\n# Takeaways\n\n- Only waveform-based methods detected phase differences between Schroeders: waveform correlation (warbleR, single cycle: effect size 0.786; Raven, repeated cycle: 0.119; warbleR, repeated cycle: 0.104) and waveform DTW (warbleR, single cycle: 0.561; repeated cycle: 0.022)\n- None of the spectrogram-based methods (spectro-temporal features, MFCC descriptors, linear and Mel frequency spectrogram cross-correlation) or Sound Analysis Pro measures detected phase differences (all effect sizes between -0.005 and 0.011, p >= 0.05)\n- Both waveform methods were much more sensitive to phase when applied to a single cycle than to repeated cycles\n- Most methods detected differences in fundamental frequency and number of harmonics. Single-cycle waveform methods were nearly insensitive to fundamental frequency (DTW: 0.004, p >= 0.05; correlation: -0.036), as resampling each cycle to 100 samples removes differences in period length\n\n</div>\n\n&nbsp;\n\n\n# Additional figures\n\nFig. 5: Shroeder 200 ms MFCCs and linear spectrograms and waveforms (the two panels were combined into a single figure outside R: `output/figures/fig5_schroeder_representations_combined.png`)\n\n::: {.cell}\n\n```{.r .numberLines .lineAnchors .cell-code}\ngrp_df <- data.frame(schr = c(\"f0-400_ncomp-7_neg.wav_1\", \"f0-400_ncomp-7_pos.wav_1\"),\n    from = c(0.05037, 0.05037), to = c(0.0554, 0.0554))\n\ngrp_df[2, 2:3] <- grp_df[2, 2:3] + 0.00121\n\nflim <- c(0, 3.5)\ncx <- 0.8\n\n\nest_200ms <- readRDS(\"./data/processed/extended_selection_table_200ms_schroeders.RDS\")\n\nest_200ms$sf <- substr(est_200ms$sound.files, start = 5, stop = 1000)\n\ngrp_df$file <- c(\"./output/figures/fig5a_schroeder_negative_phase.jpg\",\n    \"./output/figures/fig5b_schroeder_positive_phase.jpg\")\n\nfor (i in 1:nrow(grp_df)) {\n\n    jpeg(file = grp_df$file[i], width = 1600, height = 1500, res = 300)\n    wv_200ms_1 <- read_sound_file(est_200ms, index = which(est_200ms$sf ==\n        grp_df$schr[i]))\n\n    silence <- rep(0, wv_200ms_1@samp.rate/20)\n    schroeder <- c(silence, wv_200ms_1@left, silence)\n\n    sil_wv_200ms_1 <- tuneR::normalize(tuneR::Wave(schroeder, samp.rate = wv_200ms_1@samp.rate,\n        bit = 16), unit = \"16\")\n\n    mat <- matrix(c(1, 2, 6, 3, 7, 4, 8, 5), ncol = 2, byrow = TRUE)\n\n    layout(mat, widths = c(0.3, 0.9), heights = c(0.85, 0.75, 1, 1.1))\n    # layout.show(n = 8)\n\n    spc <- seewave::meanspec(wave = wv_200ms_1, plot = FALSE, ovlp = 50,\n        wl = 2100)\n\n    par(mar = c(0, 5, 1, 0))\n\n    plot(spc[, 2:1], type = \"l\", ylab = \"\", xlab = \"\", ylim = flim,\n        col = mako(10)[4], lwd = 2, xaxt = \"n\", yaxt = \"n\", xaxs = \"i\",\n        yaxs = \"i\")\n    text(x = 0.1, y = flim[2] - 0.35, labels = \"a\", cex = cx + 1)\n\n    polygon(x = spc[, 2], y = spc[, 1], col = mako(10)[4], border = NA)\n\n    axis(2, cex.axis = cx)\n\n    mtext(text = \"Frequency (kHz)\", side = 2, line = 2.4, adj = 0.5,\n        cex = cx)\n\n    # mtext(text = 'Amplitude \\n(dB) ', side = 1, line = 1.5,\n    # adj = 0.5, cex = cx)\n    mtext(text = \"Spectral\\npower\", side = 1, line = 1.5, adj = 0,\n        cex = cx, at = -0.1)\n\n    mtext(ifelse(i == 1, \"A\", \"B\"), side = 2, line = 3.8, at = 3.5,\n        las = 1, cex = 1.5)\n\n    par(mar = c(0, 0, 1, 1))\n\n    # create color palette\n    cp <- colorRampPalette(c(\"white\", \"white\", \"white\", \"white\", \"gray\",\n        \"gray\", viridis::mako(10, begin = 0.4)))\n\n    warbleR:::spectro_wrblr_int2(sil_wv_200ms_1, flim = flim, wl = 800,\n        palette = cp, grid = FALSE, collevels = seq(-60, 0, 1), ovlp = 10,\n        zp = 100, axisY = FALSE, flab = \"\", axisX = FALSE)\n\n    text(x = 0.0055, y = flim[2] - 0.35, labels = \"b\", cex = cx +\n        1)\n\n    cp2 <- colorRampPalette(c(viridis::mako(10, begin = 0.4), \"gray\",\n        \"white\"))\n\n    par(mar = c(0, 0, 0, 1))\n    mel_spectro(addsilw(sil_wv_200ms_1, at = \"start\", d = 0.002, output = \"Wave\"),\n        flim = flim, wl = 800, palette = cp2, ncep = 29, ovlp = 90,\n        axisY = FALSE, axisX = FALSE)\n\n    text(x = -0.008, y = 0.9, labels = \"c\", cex = cx + 1)\n\n    axis(2, cex.axis = cx, at = seq(0, 1, length.out = 29)[1:28],\n        labels = 1:28)\n\n    mtext(text = \"MFCCs\", side = 2, line = 2.4, adj = 0.35, cex = cx)\n\n    par(mar = c(3, 0, 0, 1))\n\n    plot(sil_wv_200ms_1@left, type = \"l\", xlab = \"\", col = mako(10)[6],\n        lwd = 1.6, xaxt = \"n\", yaxt = \"n\", xaxs = \"i\")\n\n    # add amplitude envelope\n    amp_env <- env(sil_wv_200ms_1, envt = \"abs\", ssmooth = 300, plot = FALSE)\n\n    amp_env <- amp_env * max(sil_wv_200ms_1@left)/max(amp_env)\n\n    lines(x = seq(1, length(sil_wv_200ms_1@left), length.out = nrow(amp_env)),\n        y = amp_env[, 1], col = adjustcolor(\"yellow\", alpha.f = 0.7),\n        lwd = 3)\n\n    text(x = 300, y = 20000, labels = \"d\", cex = cx + 1)\n\n    mtext(text = \"Amplitude\\n(dB)\", side = 2, line = 1, cex = cx)\n\n    indx <- round(0.101 * sil_wv_200ms_1@samp.rate, 0):round(0.106 *\n        sil_wv_200ms_1@samp.rate, 0)\n    sub <- sil_wv_200ms_1@left[indx]\n\n    lines(x = indx, y = sub, type = \"l\", col = mako(10)[9], lwd = 2)\n\n    abline(v = 0.101 * sil_wv_200ms_1@samp.rate, col = \"gray4\", lty = 2)\n\n    abline(v = 0.106 * sil_wv_200ms_1@samp.rate, col = \"gray4\", lty = 2)\n\n    at <- seq(0, length.out = 5, by = 0.2 * length(sil_wv_200ms_1@left))\n\n    labs <- seq(0, duration(sil_wv_200ms_1), length.out = 5)\n\n    at <- labs * sil_wv_200ms_1@samp.rate\n\n    axis(1, at = at, labels = labs, cex.axis = cx)\n\n    mtext(text = \"Time (s)\", side = 1, line = 2.4, adj = 0.5, cex = cx)\n\n    par(mar = c(3, 0, 1, 1))\n\n    # clp_200ms_1 <- read_sound_file(est_single, index =\n    # which(est_schr$sf == schr1)) clp_200ms_1@left <-\n    # c(clp_200ms_1@left, clp_200ms_1@left)\n\n    clp_200ms_1 <- cutw(wv_200ms_1, from = grp_df$from[i], to = grp_df$to[i],\n        output = \"Wave\", units = \"seconds\")\n\n    plot(clp_200ms_1@left, type = \"l\", ylab = \"Amplitude\", xlab = \"\",\n        col = mako(10)[8], lwd = 2.4, xaxt = \"n\", yaxt = \"n\", xaxs = \"i\")\n\n    mtext(text = \"Amplitude\\n(dB)\", side = 2, line = 1, cex = cx)\n\n    at <- seq(0, length.out = 5, by = 0.2 * length(sil_wv_200ms_1@left))\n\n    labs <- seq(0, duration(clp_200ms_1), by = 0.001)\n\n    at <- labs * sil_wv_200ms_1@samp.rate\n\n    labs <- round(labs * 1000, 2)\n\n    axis(1, at = at, labels = labs, cex.axis = cx)\n\n    mtext(text = \"Time (ms)\", side = 1, line = 2, adj = 0.5, cex = cx)\n    rect(xleft = 0, xright = duration(clp_200ms_1)/2 * sil_wv_200ms_1@samp.rate,\n        ybottom = -1e+05, ytop = 1e+06, , col = adjustcolor(\"gray\",\n            0.4), border = NA)\n\n    lines(x = seq_along(clp_200ms_1@left), y = clp_200ms_1@left, type = \"l\",\n        col = mako(10)[8], lwd = 2.4)\n\n    text(x = 5, y = 22000, labels = \"e\", cex = cx + 1)\n\n    dev.off()\n}\n```\n:::\n\n \n::: {#fig-Schroeders-multipannel layout-ncol=2}\n![400 kHz, 7 harmonic, 200ms, negative Schroeder](../output/figures/fig5a_schroeder_negative_phase.jpg){#fig-negative}\n\n![400 kHz, 7 harmonic, 200ms, positive Schroeder](../output/figures/fig5b_schroeder_positive_phase.jpg){#fig-positive}\n:::\n\nFig. 1: Zebra finch AFS example\n\n::: {.cell}\n\n```{.r .numberLines .lineAnchors .cell-code}\ndat <- imp_raven(path = \"./data/raw/additional_species/zebra_finch_from_celia/\",\n    warbler.format = TRUE, all.data = TRUE, name.from.file = TRUE,\n    ext.case = \"lower\")\n\ndat$sound.files <- \"10A_stack.wav\"\n\n\ndat <- dat[c(1, 1), ]\n\ndat$type <- c(\"AFS\", \"call\")\ndat$start[2] <- 0.01\ndat$end[2] <- 0.15\ndat$selec <- 1:2\n\nflim <- c(0, 8)\ncx <- 1\n\n\ncs <- check_sels(dat, path = \"./data/raw/additional_species/zebra_finch_from_celia/\")\n\njpeg(file = \"./output/figures/fig1_zebra_finch_call.jpg\", width = 2000,\n    height = 1200, res = 300)\n\nmat <- matrix(c(1, 2, 5, 3, 6, 4), ncol = 2, byrow = TRUE)\n\nlayout(mat, widths = c(0.3, 1), heights = c(1, 1.2, 1.2))\n\n# layout.show(n = 6)\n\nfull_call <- read_sound_file(dat, index = 2, path = \"./data/raw/additional_species/zebra_finch_from_celia/\")\n\n# power spectrum\nspc <- seewave::meanspec(wave = full_call, plot = FALSE, ovlp = 50,\n    wl = 1000, PSD = TRUE)\n\npar(mar = c(0, 4.6, 1, 0))\n\nplot(spc[, 2:1], type = \"l\", ylab = \"\", xlab = \"\", ylim = flim, col = mako(10)[4],\n    lwd = 2, xaxt = \"n\", yaxt = \"n\", xaxs = \"i\", yaxs = \"i\")\ntext(x = 0.09, y = flim[2] - 0.8, labels = \"a\", cex = cx + 1)\n\npolygon(x = spc[, 2], y = spc[, 1], col = mako(10)[4], border = NA)\n\naxis(2, cex.axis = cx)\n\npar(xpd = TRUE)  #Draw outside plot area\ntext(x = -0.47, y = 4, \"Frequency\\n(kHz)\", srt = 90, cex = 1.5)\n\npar(xpd = FALSE)  #Draw outside plot area\n\nmtext(text = \"Spectral\\npower\", side = 1, line = 2, adj = 0.1, cex = cx)\n\n\n# spectrogram\npar(mar = c(0, 0, 1, 1))\n\n# create color palette\ncp <- colorRampPalette(c(\"white\", \"white\", \"white\", \"white\", \"gray\",\n    \"gray\", viridis::mako(10, begin = 0.4)))\n\nwarbleR:::spectro_wrblr_int2(full_call, flim = flim, wl = 1000, palette = cp,\n    grid = FALSE, collevels = seq(-60, 0, 1), ovlp = 99, axisY = FALSE,\n    flab = \"\", axisX = FALSE)\n\ntext(x = 0.0024, y = flim[2] - 0.8, labels = \"b\", cex = cx + 1)\n\ncp2 <- colorRampPalette(c(viridis::mako(10, begin = 0.4), \"gray\",\n    \"white\"))\n\npar(mar = c(3, 0, 0, 1))\n\nplot(full_call@left, type = \"l\", xlab = \"\", col = mako(10)[6], lwd = 1.6,\n    xaxt = \"n\", yaxt = \"n\", xaxs = \"i\")\n\ntext(x = 100, y = max(full_call@left) * 0.9, labels = \"c\", cex = cx +\n    1)\n\nmtext(text = \"Amplitude    \\n(dB)    \", side = 2, line = 0.5, cex = cx)\n\n# add amplitude envelope\namp_env <- env(full_call, envt = \"abs\", ssmooth = 300, plot = FALSE)\n\namp_env <- amp_env * max(full_call@left)/max(amp_env)\n\nlines(x = seq(1, length(full_call@left), length.out = nrow(amp_env)),\n    y = amp_env[, 1], col = adjustcolor(\"yellow\", alpha.f = 0.7),\n    lwd = 3)\n\n\n# highlight segment\nclp_start <- 0.0451\nclp_end <- 0.0513\n\nindx <- round(clp_start * full_call@samp.rate, 0):round(clp_end *\n    full_call@samp.rate, 0)\nsub <- full_call@left[indx]\n\nlines(x = indx, y = sub, type = \"l\", col = mako(10)[9], lwd = 2)\n\n\nabline(v = clp_start * full_call@samp.rate, col = \"gray4\", lty = 2)\n\nabline(v = clp_end * full_call@samp.rate, col = \"gray4\", lty = 2)\n\nat <- seq(0, length.out = 5, by = 0.2 * length(full_call@left))\n\nlabs <- seq(0, duration(full_call), length.out = 5)\n\nat <- labs * full_call@samp.rate\n\naxis(1, at = at, labels = labs, cex.axis = cx)\n\nmtext(text = \"Time (s)\", side = 1, line = 2.1, adj = 0.5, cex = cx)\n\n# AFS waveform\npar(mar = c(3, 0, 0.5, 1))\n\n\n# clp_200ms_1 <- read_sound_file(est_single, index =\n# which(est_schr$sf == schr1)) clp_200ms_1@left <-\n# c(clp_200ms_1@left, clp_200ms_1@left)\n\nclp_call <- cutw(full_call, from = clp_start, to = clp_end, output = \"Wave\",\n    units = \"seconds\")\n\nplot(clp_call@left, type = \"l\", ylab = \"Amplitude\", xlab = \"\", col = mako(10)[8],\n    lwd = 2.4, xaxt = \"n\", yaxt = \"n\", xaxs = \"i\")\n\nmtext(text = \"Amplitude\\n(dB)\", side = 2, line = 0.5, cex = cx)\n\ndur_clp <- duration(clp_call) + 5e-05\n\nrect(xleft = dur_clp/3 * full_call@samp.rate, xright = dur_clp/3 *\n    full_call@samp.rate * 2, ybottom = -1e+05, ytop = 1e+06, , col = adjustcolor(\"gray\",\n    0.25), border = NA)\n\nrect(xleft = dur_clp/3 * full_call@samp.rate * 2, xright = dur_clp/3 *\n    full_call@samp.rate * 3, ybottom = -1e+05, ytop = 1e+06, , col = adjustcolor(\"gray\",\n    0.5), border = NA)\n\nlines(x = seq_along(clp_call@left), clp_call@left, col = mako(10)[8],\n    lwd = 2.4)\n\ntext(x = 5, y = max(clp_call@left) * 0.9, labels = \"d\", cex = cx +\n    1)\n\nlabs <- seq(0, duration(clp_call), by = 0.001)\n\nat <- labs * clp_call@samp.rate\n\nlabs <- round(labs * 1000, 2)\n\naxis(1, at = at, labels = labs, cex.axis = cx)\n\nmtext(text = \"Time (ms)\", side = 1, line = 2.1, adj = 0.5, cex = cx)\n\ndev.off()\n```\n:::\n\n \n::: {#fig-zebra-finch-multipannel layout-ncol=1}\n![Zebra finch call](../output/figures/fig1_zebra_finch_call.jpg){#fig-zebrafinch}\n:::\n\nFig. 3: Other species (only the first 3 recordings listed in the spreadsheet are used)\n\n::: {.cell}\n\n```{.r .numberLines .lineAnchors .cell-code}\nothr_sp <- readxl::read_xlsx(\"./data/raw/additional_species/AFS_FigB_SpeciesRecordingTimePoints.xlsx\")\n\nothr_sp <- as.data.frame(othr_sp)\n\n# select the string of characters before the first '_'\nothr_sp$species <- sapply(othr_sp$Recording, function(x) unlist(strsplit(x,\n    \"_\"))[1])\n\nothr_sp$species[1] <- \"Zebra finch\"\nothr_sp$species[2] <- \"White-crowned sparrow\"\nothr_sp$species[3] <- \"House wren\"\n\n\nflim <- c(0, 10)\ncx <- 1\n\njpeg(file = \"./output/figures/fig3_other_species.jpg\", width = 3000,\n    height = 1500, res = 300)\n\n\nmar <- 0.02\novlp <- 99\n\n# create color palette\ncp <- colorRampPalette(c(\"white\", \"white\", \"white\", \"white\", \"gray\",\n    \"gray\", viridis::mako(10, begin = 0.4)))\ncp2 <- colorRampPalette(c(viridis::mako(10, begin = 0.4), \"gray\",\n    \"white\"))\n\nmat <- matrix(c(1:12), ncol = 3, byrow = FALSE)\n\nlayout(mat, widths = c(1.2, 1, 1), heights = c(1.3, 1, 1.3, 1.3))\n\n# layout.show(n = 12)\n\nfor (i in 1:3) {\n    # spectrogram full recording\n\n    par_mar <- if (i == 1) {\n        c(2.5, 5, 0.45, 1)\n    } else {\n        c(2.5, 0, 0.45, 1)\n    }\n\n    par(mar = par_mar)\n\n    full_rec <- readWave(filename = file.path(\"./data/raw/additional_species/\",\n        othr_sp$Recording[i]), from = 0, to = Inf, units = \"seconds\")\n\n    warbleR:::spectro_wrblr_int2(full_rec, flim = flim, wl = if (i ==\n        3)\n        200 else 512, palette = cp, grid = FALSE, collevels = seq(-60, 0,\n        1), ovlp = ovlp, axisY = FALSE, flab = \"\", axisX = T)\n\n    mtext(text = \"Time (s)\", side = 1, line = 2.1, adj = 0.5, cex = cx)\n\n    abline(v = othr_sp$`Spectrogram_OneNote_Start(s)`[i] - mar, col = adjustcolor(\"gray4\",\n        alpha.f = 0.6), lty = 2)\n\n    abline(v = othr_sp$`Spectrogram_OneNote_End(s)`[i] + mar, col = adjustcolor(\"gray4\",\n        alpha.f = 0.6), lty = 2)\n\n    if (i == 1) {\n        par(xpd = TRUE)  #Draw outside plot area\n\n        mtext(text = \"Frequency\\n(kHz)\", side = 2, line = 2.1, adj = 0.5,\n            cex = cx)\n\n        axis(2, cex.axis = cx)\n    }\n\n    text(x = 0, y = flim[2] - 1.3, labels = othr_sp$species[i], cex = cx +\n        0.4, pos = 4)\n\n    # spectrogram 1 unit\n    par_mar <- if (i == 1) {\n        c(0, 5, 1, 1)\n    } else {\n        c(0, 0, 1, 1)\n    }\n\n    par(mar = par_mar)\n\n    full_call <- readWave(filename = file.path(\"./data/raw/additional_species/\",\n        othr_sp$Recording[i]), from = othr_sp$`Spectrogram_OneNote_Start(s)`[i] -\n        mar, to = othr_sp$`Spectrogram_OneNote_End(s)`[i] + mar, units = \"seconds\")\n\n    warbleR:::spectro_wrblr_int2(full_call, flim = flim, wl = if (i ==\n        3)\n        200 else 512, palette = cp, grid = FALSE, collevels = seq(-60, 0,\n        1), ovlp = ovlp, axisY = FALSE, flab = \"\", axisX = FALSE)\n\n    par(xpd = TRUE)  #Draw outside plot area\n\n    if (i == 1) {\n        mtext(text = \"Frequency\\n(kHz)\", side = 2, line = 2.1, adj = 0.5,\n            cex = cx)\n\n        axis(2, cex.axis = cx)\n    }\n\n    par_mar <- if (i == 1) {\n        c(3, 5, 0, 1)\n    } else {\n        c(3, 0, 0, 1)\n    }\n\n    par(mar = par_mar)\n\n    plot(full_call@left, type = \"l\", xlab = \"\", col = mako(10)[6],\n        lwd = 1.6, xaxt = \"n\", yaxt = \"n\", xaxs = \"i\", ylab = \"\")\n\n    if (i == 1) {\n        mtext(text = \"Amplitude    \\n(dB)    \", side = 2, line = 0.5,\n            cex = cx)\n    }\n\n    at <- seq(0, length.out = 5, by = 0.2 * length(full_call@left))\n\n    labs <- seq(0, duration(full_call), by = 0.05)\n\n    at <- labs * full_call@samp.rate\n\n    axis(1, at = at, labels = labs, cex.axis = cx)\n\n    mtext(text = \"Time (s)\", side = 1, line = 2.1, adj = 0.5, cex = cx)\n\n    # highlight segment\n    clp_start <- othr_sp$`FineStructure_Start(s)`[i] - othr_sp$`Spectrogram_OneNote_Start(s)`[i] +\n        mar\n    clp_end <- othr_sp$`FineStructure_End(s)`[i] - othr_sp$`Spectrogram_OneNote_Start(s)`[i] +\n        mar\n\n    indx <- round(clp_start * full_call@samp.rate, 0):round(clp_end *\n        full_call@samp.rate, 0)\n    sub <- full_call@left[indx]\n\n    par(xpd = FALSE)\n    lines(x = indx, y = sub, type = \"l\", col = mako(10)[9], lwd = 2)\n\n    abline(v = clp_start * full_call@samp.rate, col = \"gray4\", lty = 2)\n\n    abline(v = clp_end * full_call@samp.rate, col = \"gray4\", lty = 2)\n\n    # add amplitude envelope\n    amp_env <- env(full_call, envt = \"abs\", ssmooth = 300, plot = FALSE)\n\n    amp_env <- amp_env * max(full_call@left)/max(amp_env)\n\n    lines(x = seq(1, length(full_call@left), length.out = nrow(amp_env)),\n        y = amp_env[, 1], col = adjustcolor(\"yellow\", alpha.f = 0.7),\n        lwd = 3)\n\n    # AFS waveform\\\n    par_mar <- if (i == 1) {\n        c(3, 5, 0.5, 1)\n    } else {\n        c(3, 0, 0.5, 1)\n    }\n\n    par(mar = par_mar)\n\n    clp_call <- cutw(full_call, from = clp_start, to = clp_end, output = \"Wave\",\n        units = \"seconds\")\n\n    plot(clp_call@left, type = \"l\", ylab = \"\", xlab = \"\", col = mako(10)[8],\n        lwd = 2.4, xaxt = \"n\", yaxt = \"n\", xaxs = \"i\")\n\n    if (i == 1) {\n        mtext(text = \"Amplitude\\n(dB)\", side = 2, line = 0.5, cex = cx)\n    }\n\n    at <- seq(0, length.out = 5, by = 0.2 * length(clp_call@left))\n\n    labs <- seq(0, duration(clp_call), by = 0.001)\n\n    at <- labs * clp_call@samp.rate\n\n    labs <- round(labs * 1000, 2)\n\n    axis(1, at = at, labels = labs, cex.axis = cx)\n\n    mtext(text = \"Time (ms)\", side = 1, line = 2.1, adj = 0.5, cex = cx)\n}\n\ndev.off()\n```\n:::\n\n\n::: {#fig-other-species-multipannel layout-ncol=1}\n![Other species' vocalizations](../output/figures/fig3_other_species.jpg){#fig-otherspecies}\n:::\n\nFig. 4: Diagram of the sliding-window waveform comparison\n\n::: {.cell}\n\n```{.r .numberLines .lineAnchors .cell-code}\npng(file = \"./output/figures/fig4_waveform_comparison_diagram.png\",\n    width = 3100, height = 1420, res = 300)\n\nss1 <- make_single_schroeder(n.components = 7, samp.rate = 44100,\n    f0 = 400, dur = 25, save.wave = FALSE, plot = FALSE, scalar = -1,\n    color = viridis(10)[3], random.start = FALSE, add.margin = FALSE)\n\n# scale between 0 and 1\nss1@left <- (ss1@left - min(ss1@left))/(max(ss1@left) - min(ss1@left))\n\nss2 <- make_single_schroeder(n.components = 5, samp.rate = 44100,\n    f0 = 300, dur = 25, save.wave = FALSE, plot = FALSE, scalar = -1,\n    color = viridis(10)[3], random.start = FALSE, add.margin = FALSE)\n\n# scale between 0 and 1\nss2@left <- (ss2@left - min(ss2@left))/(max(ss2@left) - min(ss2@left))\n\n# remove margins dev.off()\npar(mar = c(0, 0, 0, 0))\n\ncex <- 1.2\npoint_samp <- 80\npos <- c(0, 1.5, 3, 4.6, 4.7) * 1.3\n\n# empty plot no box\nplot(1, type = \"n\", xlab = \"\", ylab = \"\", xlim = c(-0.2, 2.8), ylim = c(-7.5,\n    2), xaxt = \"n\", yaxt = \"n\", bty = \"n\", xaxs = \"i\", yaxs = \"i\")\n\ntext(x = -0.1, y = 0.5, labels = \"A\", cex = cex)\n\ntext(x = 0.5, y = -pos[1] + 1.5, labels = \"Schroeder 1\", cex = cex)\n\nlines(x = seq(0, 1, along.with = ss1@left), y = ss1@left, col = viridis(10)[3],\n    lwd = 3)\n\ntext(x = 2, y = -pos[1] + 1.5, labels = \"Schroeder 2\", cex = cex)\n\nlines(x = seq(1.2, 2.7, along.with = ss2@left), y = ss2@left, col = viridis(10)[6],\n    lwd = 3)\n\n# approx()\n\n\n\n# resample to equal size\n\ntext(x = -0.1, y = -pos[2] + 0.5, labels = \"B\", cex = cex)\n\ntext(x = 1.25, y = -pos[2] + 1.5, labels = \"Resample to equal length\",\n    cex = 1.2)\n\npoints(x = seq(0, 1, length.out = point_samp), y = approx(ss1@left,\n    n = point_samp)$y - pos[2], col = viridis(10)[3], cex = 0.7)\n\nlines(x = seq(0, 1, along.with = ss1@left), y = ss1@left - pos[2],\n    col = viridis(10, alpha = 0.3)[3], lwd = 2)\n\n\npoints(x = seq(1.2, 2.2, length.out = point_samp), y = approx(ss2@left,\n    n = point_samp)$y - pos[2], col = viridis(10)[6], cex = 0.7)\n\nlines(x = seq(1.2, 2.2, along.with = ss2@left), y = ss2@left - pos[2],\n    col = viridis(10, alpha = 0.3)[6], lwd = 2)\n\n# duplicate\ntext(x = -0.1, y = -pos[3] + 0.5, labels = \"C\", cex = cex)\n\ntext(x = 1.25, y = -pos[3] + 1.5, labels = \"Duplicate 1 Schroeder\",\n    cex = 1.2)\n\npoints(x = seq(0, 1, length.out = point_samp), y = approx(ss1@left,\n    n = point_samp)$y - pos[3], col = viridis(10)[3], cex = 0.7)\n\nlines(x = seq(0, 1, along.with = ss1@left), y = ss1@left - pos[3],\n    col = viridis(10, alpha = 0.3)[3], lwd = 2)\n\n# polygon on top\npolygon(x = c(0, 1.02, 1.02, 0) + 1, y = c(0, 0, 1, 1) - pos[3], col = adjustcolor(\"gray\",\n    alpha.f = 0.3), border = NA)\n\npolygon(x = c(-0.02, 1, 1, -0.02), y = c(0, 0, 1, 1) - pos[3], col = NA,\n    border = adjustcolor(\"gray\", alpha.f = 0.3))\n\npoints(x = seq(1, 2, length.out = point_samp), y = approx(ss1@left,\n    n = point_samp)$y - pos[3], col = viridis(10)[3], cex = 0.7, pch = 1)\n\nlines(x = seq(0, 1, along.with = ss1@left) + 1, y = ss1@left - pos[3],\n    col = viridis(10, alpha = 0.3)[3], lwd = 2)\n\n# sliding window\ntext(x = -0.1, y = -pos[4] + 0.5, labels = \"D\", cex = cex)\n\ntext(x = 1.25, y = -pos[4] + 1.5, labels = \"Sliding window matching\",\n    cex = 1.2)\n\nfor (i in 1:2) {\n    points(x = seq(i - 1, i, length.out = point_samp), y = approx(ss1@left,\n        n = point_samp)$y - pos[5] - 1, col = viridis(10)[3], cex = 0.7,\n        pch = 1)\n    lines(x = seq(0, 1, along.with = ss1@left) + i - 1, y = ss1@left -\n        pos[5] - 1, col = viridis(10, alpha = 0.3)[3], lwd = 2)\n}\n\npoints(x = seq(0, 1, length.out = point_samp) + 0.7, y = approx(ss2@left,\n    n = point_samp)$y - pos[4], col = viridis(10, alpha = 0.6)[6],\n    cex = 0.7)\n\nlines(x = seq(0, 1, along.with = ss2@left) + 0.7, y = ss2@left - pos[4],\n    col = viridis(10, alpha = 0.3)[6], lwd = 2)\n\nalpha <- 0.5\n\n# add arrow\narrows(x0 = 0.1, y0 = -pos[4] + 0.5, x1 = 1.9, y1 = -pos[4] + 0.5,\n    col = adjustcolor(\"black\", alpha.f = 0.3), length = 0.16, lwd = 2.5)\n\npos_slid <- seq(0.7, -0.2, length.out = 80)\n\n# exponential increase\nalph_slid <- exp(seq(100, 93, length.out = length(pos_slid)))\n\n# force it to range 0-0.15\nalph_slid <- alph_slid/max(alph_slid) * 0.15\n\n# alph_slid <- seq(0.15, 0, length.out = 40)\n\nfor (i in seq_along(pos_slid)) {\n\n    points(x = seq(0, 1, length.out = point_samp) + pos_slid[i], y = approx(ss2@left,\n        n = point_samp)$y - pos[4], col = viridis(10, alpha = alph_slid[i])[6],\n        cex = 0.7)\n\n}\n\ndev.off()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\npng \n  2 \n```\n\n\n:::\n:::\n\n\n![Diagram of the procedure used for pairwise comparison of Schroeder waveforms](../output/figures/fig4_waveform_comparison_diagram.png){#fig-waveform-diagram}\n\nFig. 2: Example Schroeder pairs\n\n::: {.cell}\n\n```{.r .numberLines .lineAnchors .cell-code}\njpeg(file = \"./output/figures/fig2_schroeder_examples.jpg\", width = 3000,\n    height = 1500, res = 300)\n\n\nschroeder_df <- data.frame(name = c(\"5p\", \"5n\", \"8p\", \"8n\"), n.components = c(5,\n    5, 8, 8), scalar = c(-1, 1, -1, 1), wav = c(\"f0-400_ncomp-5_pos.wav_1\",\n    \"f0-400_ncomp-5_neg.wav_1\", \"f0-400_ncomp-8_pos.wav_1\", \"f0-400_ncomp-8_neg.wav_1\"))\nschroeder_df$letter <- LETTERS[1:nrow(schroeder_df)]\n\nschroeder_df <- schroeder_df[c(3, 4, 1, 2), ]\n\n\nschroeder_df$freq_lab <- c(T, T, F, F)\nschroeder_df$amp_lab <- c(T, F, T, F)\n\nest_schr <- readRDS(\"./data/processed/extended_selection_table_200ms_schroeders.RDS\")\nest_schr$sf <- substr(est_schr$sound.files, start = 5, stop = 1000)\n\nflim <- c(0, 4)\ncx <- 1\n\nmat <- matrix(1:20, ncol = 4, byrow = TRUE)\n\nmat <- mat[c(3, 2, 4, 1, 5), ]\nmat <- cbind(21:25, mat, 26:30)\nlayout(mat, heights = c(0.3, 1, 0.3, 1, 0.5), widths = c(0.1, 0.5,\n    1, 0.5, 1, 0.05))\n\n# layout.show(n = nrow(mat) * ncol(mat))\n\nfor (i in 1:nrow(schroeder_df)) {\n    short_sch <- make_single_schroeder(n.components = schroeder_df$n.components[i],\n        samp.rate = 44100, f0 = 400, dur = 25, save.wave = FALSE,\n        plot = FALSE, scalar = schroeder_df$scalar[i], color = viridis(10)[3],\n        random.start = FALSE, add.margin = FALSE)\n    # scale between 0 and 1\n    short_sch@left <- (short_sch@left - min(short_sch@left))/(max(short_sch@left) -\n        min(short_sch@left))\n\n    lng_sch <- read_sound_file(est_schr, index = which(est_schr$sf ==\n        schroeder_df$wav[i]))\n\n    spc <- seewave::meanspec(wave = lng_sch, plot = FALSE, ovlp = 50,\n        wl = 2100, PSD = TRUE)\n\n    par(mar = c(0, 1, 0, 0))\n\n    plot(spc[, 1:2], type = \"l\", ylab = \"\", xlab = \"\", xlim = flim,\n        col = mako(10)[4], lwd = 2, xaxt = \"n\", yaxt = \"n\", xaxs = \"i\",\n        yaxs = \"i\")\n    text(x = 0.1, y = flim[2] - 0.2, labels = \"a\", cex = cx + 1)\n    polygon(x = spc[, 1], y = spc[, 2], col = mako(10)[4], border = NA)\n\n    mtext(text = paste0(\"                                                               \",\n        schroeder_df$n.components[i], \" components, \", ifelse(schroeder_df$scalar[i] ==\n            1, \"positive phase\", \"negative phase\")), side = 3, line = 1,\n        cex = cx)\n\n    if (schroeder_df$freq_lab[i]) {\n        axis(1, cex.axis = cx)\n        mtext(text = \"Frequency (kHz)\", side = 1, line = 2.4, adj = 0.5,\n            cex = cx)\n    }\n\n    if (schroeder_df$amp_lab[i])\n        mtext(text = \"Spectral power     \", side = 2, line = 1, adj = 0.5,\n            cex = cx)\n\n    mtext(schroeder_df$letter[i], side = 2, line = -1, at = 1.1, las = 1,\n        cex = 1.5)\n\n    if (i %in% c(1, 3))\n        par(mar = c(0, 2, 0, 0)) else par(mar = c(0, 0, 0, 0))\n\n    plot(short_sch@left, type = \"l\", ylab = \"\", xlab = \"\", col = mako(10)[8],\n        lwd = 2.4, xaxt = \"n\", yaxt = \"n\", xaxs = \"i\")\n\n    if (i %in% c(1, 3))\n        mtext(text = \"Amplitude\", side = 2, line = 0.4, adj = 0.5,\n            cex = cx)\n\n    at <- seq(0, length.out = 5, by = 0.2 * length(lng_sch@left))\n\n    labs <- seq(0, duration(short_sch), length.out = 5)\n\n    at <- labs * lng_sch@samp.rate\n\n    labs <- round(labs * 1000, 1)\n\n    if (schroeder_df$freq_lab[i]) {\n        axis(1, at = at, labels = labs, cex.axis = cx)\n        mtext(text = \"Time (ms)\", side = 1, line = 2.4, adj = 0.5,\n            cex = cx)\n    }\n}\n\ndev.off()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\npng \n  2 \n```\n\n\n:::\n:::\n\n\n![Example Schroeder-phase signal pairs (positive and negative) with 5 and 8 components](../output/figures/fig2_schroeder_examples.jpg){#fig-schroeder-examples}\n\n---\n\n# Session information {.unnumbered}\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n─ Session info ───────────────────────────────────────────────────────────────\n setting  value\n version  R version 4.6.1 (2026-06-24 ucrt)\n os       Windows 11 x64 (build 22631)\n system   x86_64, mingw32\n ui       RTerm\n language (EN)\n collate  Spanish_Costa Rica.utf8\n ctype    Spanish_Costa Rica.utf8\n tz       America/Costa_Rica\n date     2026-10-04\n pandoc   3.8.3 @ C:\\\\Program Files\\\\RStudio\\\\resources\\\\app\\\\bin\\\\quarto\\\\bin\\\\tools/ (via rmarkdown)\n quarto   NA\n\n─ Packages ───────────────────────────────────────────────────────────────────\n package          * version   date (UTC) lib source\n abind              1.4-8     2024-09-12 [1] CRAN (R 4.6.0)\n backports          1.5.1     2026-04-03 [1] CRAN (R 4.6.0)\n baRulho          * 2.1.7     2026-10-04 [1] Github (maRce10/baRulho@435225e)\n bitops             1.1-0     2026-07-30 [1] CRAN (R 4.6.1)\n brio               1.1.5     2024-04-24 [1] CRAN (R 4.6.1)\n cachem             1.1.0     2024-05-16 [1] CRAN (R 4.6.1)\n cellranger         1.1.0     2016-07-27 [1] CRAN (R 4.6.1)\n checkmate          2.3.4     2026-02-03 [1] CRAN (R 4.6.1)\n class              7.3-23    2025-01-01 [2] CRAN (R 4.6.1)\n classInt           0.4-11    2025-01-08 [1] CRAN (R 4.6.1)\n cli                3.6.6     2026-04-09 [1] CRAN (R 4.6.1)\n cluster            2.1.8.2   2026-02-05 [2] CRAN (R 4.6.1)\n codetools          0.2-20    2024-03-31 [2] CRAN (R 4.6.1)\n crayon             1.5.3     2024-06-20 [1] CRAN (R 4.6.1)\n curl               7.1.0     2026-04-22 [1] CRAN (R 4.6.1)\n DBI                1.3.0     2026-02-25 [1] CRAN (R 4.6.1)\n deldir             2.0-4     2024-02-28 [1] CRAN (R 4.6.1)\n Deriv              4.3.0     2026-07-23 [1] CRAN (R 4.6.1)\n devtools           2.5.2     2026-04-30 [1] CRAN (R 4.6.1)\n digest             0.6.39    2025-11-19 [1] CRAN (R 4.6.1)\n dplyr              1.2.1     2026-04-03 [1] CRAN (R 4.6.1)\n dtw              * 1.23-3    2026-06-09 [1] CRAN (R 4.6.1)\n e1071              1.7-17    2025-12-18 [1] CRAN (R 4.6.1)\n ecodist          * 2.1.3     2023-10-30 [1] CRAN (R 4.6.1)\n ellipsis           0.3.3     2026-04-04 [1] CRAN (R 4.6.1)\n evaluate           1.0.5     2025-08-27 [1] CRAN (R 4.6.1)\n farver             2.1.2     2024-05-13 [1] CRAN (R 4.6.1)\n fastmap            1.2.0     2024-05-15 [1] CRAN (R 4.6.1)\n fftw               1.0-9     2024-09-20 [1] CRAN (R 4.6.0)\n formatR          * 1.14      2023-01-17 [1] CRAN (R 4.6.1)\n fs                 2.1.0     2026-04-18 [1] CRAN (R 4.6.1)\n generics           0.1.4     2025-05-09 [1] CRAN (R 4.6.1)\n ggplot2          * 4.0.3     2026-04-22 [1] CRAN (R 4.6.1)\n glue               1.8.1     2026-04-17 [1] CRAN (R 4.6.1)\n goftest            1.2-3     2021-10-07 [1] CRAN (R 4.6.1)\n gridExtra          2.3.1     2026-06-25 [1] CRAN (R 4.6.1)\n gtable             0.3.6     2024-10-25 [1] CRAN (R 4.6.1)\n htmltools          0.5.9     2025-12-04 [1] CRAN (R 4.6.1)\n htmlwidgets        1.6.4     2023-12-06 [1] CRAN (R 4.6.1)\n httr               1.4.8     2026-02-13 [1] CRAN (R 4.6.1)\n igraph             2.3.3     2026-06-26 [1] CRAN (R 4.6.1)\n jsonlite           2.0.0     2025-03-27 [1] CRAN (R 4.6.1)\n kableExtra       * 1.4.1     2026-07-08 [1] CRAN (R 4.6.1)\n KernSmooth         2.23-26   2025-01-01 [2] CRAN (R 4.6.1)\n knitr            * 1.51      2025-12-20 [1] CRAN (R 4.6.1)\n lattice            0.22-9    2026-02-09 [2] CRAN (R 4.6.1)\n lifecycle          1.0.5     2026-01-08 [1] CRAN (R 4.6.1)\n magrittr           2.0.5     2026-04-04 [1] CRAN (R 4.6.1)\n MASS               7.3-65    2025-02-28 [2] CRAN (R 4.6.1)\n Matrix             1.7-5     2026-03-21 [2] CRAN (R 4.6.1)\n memoise            2.0.1     2021-11-26 [1] CRAN (R 4.6.1)\n mgcv               1.9-4     2025-11-07 [2] CRAN (R 4.6.1)\n NatureSounds     * 1.0.5     2025-01-17 [1] CRAN (R 4.6.1)\n nicheROVER         1.1.2     2023-10-13 [1] CRAN (R 4.6.1)\n nlme               3.1-169   2026-03-27 [2] CRAN (R 4.6.1)\n numform          * 0.7.0     2021-10-09 [1] CRAN (R 4.6.1)\n ohun             * 1.0.4     2025-10-22 [1] CRAN (R 4.6.1)\n otel               0.2.0     2025-08-29 [1] CRAN (R 4.6.1)\n packrat            0.9.3     2025-06-16 [1] CRAN (R 4.6.1)\n pbapply            1.7-4     2025-07-20 [1] CRAN (R 4.6.1)\n permute            0.9-10    2026-02-06 [1] CRAN (R 4.6.1)\n PhenotypeSpace   * 0.1.1     2026-10-04 [1] Github (maRce10/PhenotypeSpace@6e3b9a8)\n pillar             1.11.1    2025-09-17 [1] CRAN (R 4.6.1)\n pkgbuild           1.4.8     2025-05-26 [1] CRAN (R 4.6.1)\n pkgconfig          2.0.3     2019-09-22 [1] CRAN (R 4.6.1)\n pkgload            1.5.3     2026-06-15 [1] CRAN (R 4.6.1)\n png                0.1-9     2026-03-15 [1] CRAN (R 4.6.0)\n polyclip           1.10-7    2024-07-23 [1] CRAN (R 4.6.1)\n proxy            * 0.4-29    2025-12-29 [1] CRAN (R 4.6.1)\n purrr              1.2.2     2026-04-10 [1] CRAN (R 4.6.1)\n R6                 2.6.1     2025-02-15 [1] CRAN (R 4.6.1)\n ragg               1.5.2     2026-03-23 [1] CRAN (R 4.6.1)\n raster             3.6-32    2025-03-28 [1] CRAN (R 4.6.1)\n RColorBrewer       1.1-3     2022-04-03 [1] CRAN (R 4.6.0)\n Rcpp               1.1.2     2026-07-05 [1] CRAN (R 4.6.1)\n RCurl              1.98-1.19 2026-06-03 [1] CRAN (R 4.6.1)\n readxl           * 1.5.0     2026-05-16 [1] CRAN (R 4.6.1)\n remotes            2.5.0     2024-03-17 [1] CRAN (R 4.6.1)\n rjson              0.2.23    2024-09-16 [1] CRAN (R 4.6.0)\n rlang              1.3.0     2026-07-05 [1] CRAN (R 4.6.1)\n rmarkdown          2.32      2026-09-01 [1] CRAN (R 4.6.1)\n Rraven           * 1.0.16    2025-10-23 [1] CRAN (R 4.6.1)\n rstudioapi         0.19.0    2026-06-11 [1] CRAN (R 4.6.1)\n S7                 0.2.2     2026-04-22 [1] CRAN (R 4.6.1)\n scales             1.4.0     2025-04-24 [1] CRAN (R 4.6.1)\n seewave          * 2.2.4     2025-08-19 [1] CRAN (R 4.6.1)\n sessioninfo        1.2.4     2026-06-04 [1] CRAN (R 4.6.1)\n sf                 1.1-3     2026-09-11 [1] CRAN (R 4.6.1)\n signal             1.8-1     2024-06-26 [1] CRAN (R 4.6.1)\n Sim.DiffProc       5.0       2025-12-13 [1] CRAN (R 4.6.1)\n sketchy            1.0.5     2025-01-16 [1] CRAN (R 4.6.1)\n soundgen         * 3.0.0     2026-09-20 [1] CRAN (R 4.6.1)\n sp                 2.2-3     2026-07-19 [1] CRAN (R 4.6.1)\n spatstat.data      3.1-9     2025-10-18 [1] CRAN (R 4.6.1)\n spatstat.explore   3.8-3     2026-09-23 [1] CRAN (R 4.6.1)\n spatstat.geom      3.8-3     2026-09-18 [1] CRAN (R 4.6.1)\n spatstat.random    3.5-2     2026-09-22 [1] CRAN (R 4.6.1)\n spatstat.sparse    3.2-0     2026-05-21 [1] CRAN (R 4.6.1)\n spatstat.univar    3.2-0     2026-05-18 [1] CRAN (R 4.6.1)\n spatstat.utils     3.2-5     2026-09-11 [1] CRAN (R 4.6.1)\n stringi            1.8.9     2026-08-04 [1] CRAN (R 4.6.1)\n stringr            1.6.0     2025-11-04 [1] CRAN (R 4.6.1)\n svglite            2.2.2     2025-10-21 [1] CRAN (R 4.6.1)\n systemfonts        1.3.2     2026-03-05 [1] CRAN (R 4.6.1)\n tensor             1.5.1     2025-06-17 [1] CRAN (R 4.6.1)\n terra              1.9-50    2026-09-08 [1] CRAN (R 4.6.1)\n testthat           3.3.2     2026-01-11 [1] CRAN (R 4.6.1)\n textshaping        1.0.5     2026-03-06 [1] CRAN (R 4.6.1)\n tibble             3.3.1     2026-01-11 [1] CRAN (R 4.6.1)\n tidyselect         1.2.1     2024-03-11 [1] CRAN (R 4.6.1)\n tuneR            * 1.4.7     2024-04-17 [1] CRAN (R 4.6.1)\n units              1.0-1     2026-03-11 [1] CRAN (R 4.6.1)\n usethis            3.2.1     2025-09-06 [1] CRAN (R 4.6.1)\n vctrs              0.7.3     2026-04-11 [1] CRAN (R 4.6.1)\n vegan              2.7-5     2026-05-25 [1] CRAN (R 4.6.1)\n viridis          * 0.6.5     2024-01-29 [1] CRAN (R 4.6.1)\n viridisLite      * 0.4.3     2026-02-04 [1] CRAN (R 4.6.1)\n warbleR          * 1.1.37    2025-10-22 [1] CRAN (R 4.6.1)\n withr              3.0.3     2026-06-19 [1] CRAN (R 4.6.1)\n xaringanExtra      0.8.0     2024-05-19 [1] CRAN (R 4.6.1)\n xfun               0.60      2026-07-09 [1] CRAN (R 4.6.1)\n xml2               1.6.0     2026-06-22 [1] CRAN (R 4.6.1)\n yaml               2.3.12    2025-12-10 [1] CRAN (R 4.6.1)\n\n [1] C:/Users/Biologia-UCR/AppData/Local/R/win-library/4.6\n [2] C:/Program Files/R/R-4.6.1/library\n * ── Packages attached to the search path.\n\n──────────────────────────────────────────────────────────────────────────────\n```\n\n\n:::\n:::\n\n\n\n",
    "supporting": [
      "1_schroeder_synthesis_and_method_comparison_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}